"""
zipmi.scapy_ipmi.oem.dell_generated — auto-generated from
the Dell iDRAC6 fullfw dispatch-table RE.

DO NOT EDIT BY HAND. Regenerate with:
    python -m zipmi.parsers.md_table > zipmi/scapy_ipmi/oem/dell_generated.py

Source: /Volumes/yyy/phd/bmc/dell/fullfw-ipmi-commands.md
Entries: 192
"""

from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class DellEntry:
    name: str
    priv: str
    sessionless: bool
    handler_addr: int | None
    live_status: str
    not_present: bool
    description: str

DELL_DISPATCH: dict[tuple[int, int], DellEntry] = {
    (0x00, 0x00): DellEntry(name='CmdGetChassisCapabilities', priv='User', sessionless=False, handler_addr=None, live_status='YES: 01 20 20 20 20 20', not_present=False, description='Returns chassis capabilities: intrusion sensor, all devices at BMC 0x20'),
    (0x00, 0x01): DellEntry(name='CmdGetChassisStatus', priv='User', sessionless=False, handler_addr=None, live_status='YES: 21 10 00 50', not_present=False, description='Power ON, restore=previous, last on via IPMI'),
    (0x00, 0x02): DellEntry(name='CmdChassisControl', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Power off / on / cycle / hard reset / diagnostic interrupt / soft shutdown'),
    (0x00, 0x04): DellEntry(name='DellCmdChassisIdentify', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Blink chassis identify LED (Dell override of standard identify)'),
    (0x00, 0x05): DellEntry(name='CmdSetChassisCapabilities', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write chassis capability bytes'),
    (0x00, 0x07): DellEntry(name='CmdGetSystemRestartCause', priv='User', sessionless=False, handler_addr=None, live_status='YES: 01 01', not_present=False, description='Restart cause 0x01 = chassis control command, channel 0x01'),
    (0x00, 0x08): DellEntry(name='CmdSetSystemBootOptions', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set boot flags: boot device, BIOS quiet mode, lock out reset buttons'),
    (0x00, 0x09): DellEntry(name='CmdGetSystemBootOptions', priv='Operator', sessionless=False, handler_addr=None, live_status='YES: 0xC7 (needs param byte)', not_present=False, description='Read current boot option parameters'),
    (0x00, 0x0b): DellEntry(name='CmdSetPowerCycleInterval', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set delay (seconds) between power-off and power-on during a power cycle'),
    (0x04, 0x00): DellEntry(name='CmdSetEventReceiver', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set IPMB address and LUN of event message receiver'),
    (0x04, 0x01): DellEntry(name='CmdGetEventReceiver', priv='User', sessionless=False, handler_addr=None, live_status='YES: 20 00', not_present=False, description='Event receiver at BMC (0x20), LUN 0'),
    (0x04, 0x02): DellEntry(name='CmdPlatformEvent', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Generate a platform event message'),
    (0x04, 0x10): DellEntry(name='CmdPEFCGetCapabilities', priv='User', sessionless=False, handler_addr=None, live_status='YES: 51 1f 28', not_present=False, description='PEF v1.5, 31 filter entries, 40 alert policies'),
    (0x04, 0x11): DellEntry(name='CmdPEFCArmPostponeTimer', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Arm or postpone the PEF postpone timer'),
    (0x04, 0x12): DellEntry(name='CmdPEFCSetConfigurationParameters', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write PEF configuration'),
    (0x04, 0x13): DellEntry(name='CmdPEFCGetConfigurationParameters', priv='Operator', sessionless=True, handler_addr=None, live_status='YES: 0xC7 (needs param byte)', not_present=False, description='Read PEF configuration parameters'),
    (0x04, 0x14): DellEntry(name='CmdPEFCSetLastProcessedEventID', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set record ID of most recently processed SEL event'),
    (0x04, 0x15): DellEntry(name='CmdPEFCGetLastProcessedEventID', priv='User', sessionless=False, handler_addr=None, live_status='YES: 81 5b c4 69 07 00 ff ff 07 00', not_present=False, description='Last processed event IDs'),
    (0x04, 0x16): DellEntry(name='CmdPEFCAlertImmediate', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Force immediate alert transmission'),
    (0x04, 0x17): DellEntry(name='CmdPETCAcknowledge', priv='Unspecified', sessionless=False, handler_addr=None, live_status='YES: 0xC7 (needs data)', not_present=False, description='Acknowledge a PET SNMP trap'),
    (0x04, 0x23): DellEntry(name='CmdGetSensorReadingFactors', priv='User', sessionless=False, handler_addr=None, live_status='DISABLED (0xC1)', not_present=False, description='Dell stub 0x00161140 — confirmed disabled on live BMC'),
    (0x04, 0x24): DellEntry(name='CmdSetSensorHysteresis', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set hysteresis for threshold-based sensor'),
    (0x04, 0x25): DellEntry(name='CmdGetSensorHysteresis', priv='User', sessionless=False, handler_addr=None, live_status='YES: 0xC7 (needs 2-byte sensor#)', not_present=False, description='Read hysteresis values'),
    (0x04, 0x26): DellEntry(name='CmdSetSensorThresholds', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write threshold values'),
    (0x04, 0x27): DellEntry(name='CmdGetSensorThresholds', priv='User', sessionless=False, handler_addr=None, live_status='YES: 18 00 00 00 d5 da 00 (sensor 1)', not_present=False, description='Sensor 1 thresholds: UC=0xD5, UNR=0xDA'),
    (0x04, 0x28): DellEntry(name='CmdSetSensorEventEnable', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Enable/disable event generation per sensor'),
    (0x04, 0x29): DellEntry(name='CmdGetSensorEventEnable', priv='User', sessionless=False, handler_addr=None, live_status='YES: 00 (sensor 1)', not_present=False, description='Sensor 1 events: none enabled'),
    (0x04, 0x2a): DellEntry(name='CmdRearmSensorEvents', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Re-arm event generation'),
    (0x04, 0x2b): DellEntry(name='CmdGetSensorEventStatus', priv='User', sessionless=False, handler_addr=None, live_status='YES: 00 00 (sensor 1)', not_present=False, description='Sensor 1 event status: no events'),
    (0x04, 0x2d): DellEntry(name='CmdGetSensorReading', priv='User', sessionless=False, handler_addr=None, live_status='YES: 42 00 c0 (sensor 1)', not_present=False, description='Sensor 1 reading=0x42, scanning enabled'),
    (0x04, 0x30): DellEntry(name='CmdSetSensorReading', priv='Operator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Inject arbitrary reading/event status'),
    (0x06, 0x01): DellEntry(name='CmdGetDeviceID', priv='User', sessionless=False, handler_addr=None, live_status='YES: 20 80 01 70 02 df a2 02 00 ...', not_present=False, description='FW 1.70, IPMI 2.0, Dell IANA 674'),
    (0x06, 0x02): DellEntry(name='CmdColdReset', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (DESTRUCTIVE)', not_present=False, description='Unconditionally reset the BMC'),
    (0x06, 0x04): DellEntry(name='CmdGetSelfTestResults', priv='User', sessionless=False, handler_addr=None, live_status='YES: 55 00', not_present=False, description='Self-test passed, no errors'),
    (0x06, 0x05): DellEntry(name='CmdManufacturingTestOn', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Enable manufacturing test mode'),
    (0x06, 0x06): DellEntry(name='CmdSetACPIPowerState', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set ACPI power state'),
    (0x06, 0x07): DellEntry(name='CmdGetACPIPowerState', priv='User', sessionless=False, handler_addr=None, live_status='YES: 2a 2a', not_present=False, description='System=S0/G0(working), Device=D0(on)'),
    (0x06, 0x08): DellEntry(name='CmdGetDeviceGUID', priv='User', sessionless=False, handler_addr=None, live_status='YES: 44 45 4c 4c 58 00 10 54 80 33 b5 c0 4f 47 51 31', not_present=False, description='GUID = "DELLX..T.3..OGQ1"'),
    (0x06, 0x09): DellEntry(name='CmdGetNetFnSupport', priv='User', sessionless=False, handler_addr=None, live_status='YES: 0xC7 (needs channel/LUN param)', not_present=False, description='Bitmap of supported NetFns'),
    (0x06, 0x0a): DellEntry(name='CmdGetCommandSupport', priv='Operator', sessionless=True, handler_addr=None, live_status='YES: 0xCC (needs NetFn/channel param)', not_present=False, description='Command support bitmap'),
    (0x06, 0x0b): DellEntry(name='CmdGetCommandSubFnSupport', priv='Administrator', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Sub-function support bitmap'),
    (0x06, 0x0c): DellEntry(name='CmdGetConfigurableCommands', priv='Operator', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='Configurable commands bitmap'),
    (0x06, 0x0d): DellEntry(name='CmdGetConfigurableCommandSubFn', priv='Administrator', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Configurable sub-functions'),
    (0x06, 0x22): DellEntry(name='CmdResetWatchdogTimer', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Pet the watchdog timer'),
    (0x06, 0x24): DellEntry(name='CmdSetWatchdogTimer', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Configure watchdog'),
    (0x06, 0x25): DellEntry(name='CmdGetWatchdogTimer', priv='User', sessionless=False, handler_addr=None, live_status='YES: c4 00 00 00 c0 12 79 12', not_present=False, description='Watchdog config + countdown'),
    (0x06, 0x2e): DellEntry(name='CmdSetBMCGlobalEnable', priv='Unspecified', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Enable/disable message handling'),
    (0x06, 0x2f): DellEntry(name='CmdGetBMCGlobalEnable', priv='User', sessionless=False, handler_addr=None, live_status='YES: 0c', not_present=False, description='Global enables: SEL+EventMsgBuf enabled'),
    (0x06, 0x30): DellEntry(name='CmdClearMsgFlags', priv='Unspecified', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Clear message flag bits'),
    (0x06, 0x31): DellEntry(name='CmdGetMsgFlags', priv='Unspecified', sessionless=True, handler_addr=None, live_status='NO (0xC1)', not_present=False, description='Not available on LAN — KCS system interface only'),
    (0x06, 0x32): DellEntry(name='CmdEnableMsgChannelRecv', priv='Unspecified', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='Enable channel receive'),
    (0x06, 0x33): DellEntry(name='CmdGetMsg', priv='Unspecified', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='Retrieve from receive queue'),
    (0x06, 0x35): DellEntry(name='CmdReadEventMsgBuf', priv='Unspecified', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='Read from event message buffer'),
    (0x06, 0x37): DellEntry(name='CmdGetSystemGUID', priv='Unspecified', sessionless=False, handler_addr=None, live_status='YES: 44 45 4c 4c 58 00 10 54 80 33 b5 c0 4f 47 51 31', not_present=False, description='Same as DeviceGUID'),
    (0x06, 0x3c): DellEntry(name='CmdCloseSession', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Close IPMI session'),
    (0x06, 0x3d): DellEntry(name='CmdGetSessionInfo', priv='Administrator', sessionless=True, handler_addr=None, live_status='YES: 20 05 01 02 04 01 c0 a8 00 02 b0 be 83 a2 52 c5 dd d1', not_present=False, description='Current session: from 192.168.0.2, MAC b0:be:83:a2:52:c5'),
    (0x06, 0x3f): DellEntry(name='CmdGetAuthCode', priv='Operator', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Generate auth code'),
    (0x06, 0x40): DellEntry(name='CmdSetChannelAccess', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set channel access mode'),
    (0x06, 0x41): DellEntry(name='CmdGetChannelAccess', priv='User', sessionless=False, handler_addr=None, live_status='YES: 12 04 (ch1, volatile)', not_present=False, description='Ch1: always available, max priv=Admin'),
    (0x06, 0x42): DellEntry(name='CmdGetChannelInfo', priv='User', sessionless=False, handler_addr=None, live_status='YES: 01 04 01 81 f2 1b 00 00 00 (ch1)', not_present=False, description='Ch1: 802.3 LAN, IPMB-1.0, multi-session'),
    (0x06, 0x43): DellEntry(name='CmdSetUserAccess', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set user privilege level'),
    (0x06, 0x44): DellEntry(name='CmdGetUserAccess', priv='Operator', sessionless=False, handler_addr=None, live_status='YES: 10 88 01 0f (ch1 user1)', not_present=False, description='16 user slots, user1 enabled, Admin priv'),
    (0x06, 0x45): DellEntry(name='CmdSetUserName', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write user name'),
    (0x06, 0x46): DellEntry(name='CmdGetUserName', priv='Operator', sessionless=False, handler_addr=None, live_status='YES: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (user1)', not_present=False, description='User 1 name = null (anonymous/root)'),
    (0x06, 0x47): DellEntry(name='CmdSetUserPassword', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set/test user password'),
    (0x06, 0x48): DellEntry(name='CmdActivatePayload', priv='Callback', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Activate SOL/OEM payload'),
    (0x06, 0x49): DellEntry(name='CmdDeactivatePayload', priv='Callback', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Deactivate payload'),
    (0x06, 0x4a): DellEntry(name='CmdGetPayloadActivationStatus', priv='User', sessionless=False, handler_addr=None, live_status='YES: 01 00 00 (SOL)', not_present=False, description='SOL: 1 instance max, 0 active'),
    (0x06, 0x4b): DellEntry(name='CmdGetPayloadInstanceInfo', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Payload instance info'),
    (0x06, 0x4c): DellEntry(name='CmdSetUserPayloadAccess', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set user payload access'),
    (0x06, 0x4d): DellEntry(name='CmdGetUserPayloadAccess', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='User payload access bitmap'),
    (0x06, 0x4e): DellEntry(name='CmdGetChannelPayloadSupport', priv='User', sessionless=False, handler_addr=None, live_status='YES: 03 00 3f 00 00 00 00 00 (ch1)', not_present=False, description='Ch1: IPMI+SOL standard, 6 OEM payloads'),
    (0x06, 0x4f): DellEntry(name='CmdGetChannelPayloadVersion', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Payload version'),
    (0x06, 0x50): DellEntry(name='CmdGetChannelOEMPayloadInfo', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='OEM payload info'),
    (0x06, 0x52): DellEntry(name='CmdSuspendBMCARPs', priv='Operator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Gratuitous ARP and ARP response suspend/resume for a LAN channel'),
    (0x06, 0x54): DellEntry(name='CmdGetChannelCipherSuites', priv='Operator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Enumerate supported cipher suites per channel'),
    (0x06, 0x55): DellEntry(name='CmdSuspendResumePayloadEncryption', priv='User', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Temporarily suspend/resume payload encryption on active session'),
    (0x06, 0x56): DellEntry(name='CmdSetChannelSecurityKeys', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Set or clear integrity/confidentiality keys for a channel'),
    (0x06, 0x60): DellEntry(name='CmdSetCommandEnables', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Enable/disable specific commands (command firewall write)'),
    (0x06, 0x61): DellEntry(name='CmdGetCommandEnables', priv='Operator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Read command enable bitmap'),
    (0x06, 0x62): DellEntry(name='CmdSetCommandSubFnEnables', priv='Administrator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Enable/disable sub-functions of a specific command'),
    (0x06, 0x63): DellEntry(name='CmdGetCommandSubFnEnables', priv='User', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Read sub-function enable bitmap'),
    (0x06, 0x64): DellEntry(name='CmdSet/GetSessionLessChannelPrivilege', priv='Operator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Get or set privilege level on session-less channels (e.g., KCS)'),
    (0x08, 0x02): DellEntry(name='CmdFirmwareUpdate', priv='Administrator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Initiate firmware update process'),
    (0x08, 0x10): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command (chunk write)'),
    (0x08, 0x11): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x08, 0x12): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x08, 0x13): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x08, 0x14): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x08, 0x15): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x08, 0x16): DellEntry(name='(FW phase cmd)', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='Firmware update sub-command'),
    (0x0a, 0x10): DellEntry(name='CmdGetFRUInvAreaInfo', priv='User', sessionless=False, handler_addr=None, live_status='YES: 00 10 00 (dev 0)', not_present=False, description='FRU area: 4096 bytes (0x1000), byte access'),
    (0x0a, 0x11): DellEntry(name='CmdReadFRUData', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Read bytes from FRU inventory data area'),
    (0x0a, 0x12): DellEntry(name='CmdWriteFRUData', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write FRU data. Can overwrite serial numbers'),
    (0x0a, 0x20): DellEntry(name='CmdGetSDRRepoInfo', priv='User', sessionless=False, handler_addr=None, live_status='YES: 51 7e 00 e1 05 ff ff ff ff ff ff ff ff 42', not_present=False, description='126 SDRs, 1505 bytes free, v1.5'),
    (0x0a, 0x22): DellEntry(name='CmdResvSDRRepo', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Reserve SDR repository'),
    (0x0a, 0x23): DellEntry(name='CmdGetSDR', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Read SDR by ID'),
    (0x0a, 0x25): DellEntry(name='CmdPartAddSDR', priv='Operator', sessionless=True, handler_addr=None, live_status='DISABLED (0xC1)', not_present=False, description='Dell stub 0x00161140 — confirmed disabled'),
    (0x0a, 0x27): DellEntry(name='CmdClrSDR', priv='Administrator', sessionless=False, handler_addr=None, live_status='DISABLED (0xC1)', not_present=False, description='Dell stub 0x00161140 — confirmed disabled'),
    (0x0a, 0x28): DellEntry(name='CmdGetSDRRepoTime', priv='User', sessionless=False, handler_addr=None, live_status='YES: a8 e5 d3 69', not_present=False, description='SDR repo timestamp (Unix time)'),
    (0x0a, 0x29): DellEntry(name='CmdSetSDRRepoTime', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set SDR timestamp'),
    (0x0a, 0x2c): DellEntry(name='CmdRunInitAgent', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Run sensor init agent'),
    (0x0a, 0x40): DellEntry(name='CmdGetSELInfo', priv='User', sessionless=False, handler_addr=None, live_status='YES: 51 07 00 90 1f 81 5b c4 69 95 fc 46 4d 02', not_present=False, description='7 entries, 8080 bytes free, v1.5'),
    (0x0a, 0x42): DellEntry(name='CmdReserveSEL', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Reserve SEL'),
    (0x0a, 0x43): DellEntry(name='CmdGetSELEntry', priv='User', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Read SEL record by ID'),
    (0x0a, 0x44): DellEntry(name='CmdAddSELEntry', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Add event record to SEL'),
    (0x0a, 0x47): DellEntry(name='CmdClearSEL', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (DESTRUCTIVE)', not_present=False, description='Erase entire SEL'),
    (0x0a, 0x48): DellEntry(name='CmdGetSELTime', priv='User', sessionless=False, handler_addr=None, live_status='YES: a8 e5 d3 69', not_present=False, description='SEL clock (Unix timestamp)'),
    (0x0a, 0x49): DellEntry(name='CmdSetSELTime', priv='Administrator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set SEL clock time'),
    (0x0c, 0x01): DellEntry(name='CmdSetLANConfigParam', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write LAN config: IP, subnet, gateway, VLAN'),
    (0x0c, 0x02): DellEntry(name='CmdGetLANConfigParam', priv='Operator', sessionless=False, handler_addr=None, live_status='YES: 11 c0 a8 00 17 (ch1 param3=IP)', not_present=False, description='LAN IP = 192.168.0.23'),
    (0x0c, 0x10): DellEntry(name='CmdSetSerModemConfigParam', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Write serial/modem config'),
    (0x0c, 0x11): DellEntry(name='CmdGetSerModemConfigParam', priv='Operator', sessionless=False, handler_addr=None, live_status='?', not_present=False, description='Read serial/modem config'),
    (0x0c, 0x12): DellEntry(name='CmdSetSerModemMux', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Control serial port mux'),
    (0x0c, 0x1c): DellEntry(name='CmdSetSOLConfiguration', priv='Operator', sessionless=False, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Set SOL parameters'),
    (0x0c, 0x21): DellEntry(name='CmdSetSOLConfiguration (Dell)', priv='Administrator', sessionless=True, handler_addr=None, live_status='? (WRITES)', not_present=False, description='Dell-extended SOL config set'),
    (0x0c, 0x22): DellEntry(name='CmdGetSOLConfiguration', priv='User', sessionless=False, handler_addr=None, live_status='YES: 11 01 (ch1 param1=enable)', not_present=False, description='SOL enabled'),
    (0x2e, 0x01): DellEntry(name='0x00174724', priv='User', sessionless=False, handler_addr=None, live_status='', not_present=False, description='OEM/Group command (Dell IANA 0x0002A2 prefix required)'),
    (0x2e, 0x02): DellEntry(name='0x0017488c', priv='User', sessionless=True, handler_addr=None, live_status='', not_present=False, description='OEM/Group command'),
    (0x2e, 0x03): DellEntry(name='0x00174c68', priv='Administrator', sessionless=True, handler_addr=None, live_status='', not_present=False, description='OEM/Group command'),
    (0x2e, 0x04): DellEntry(name='0x00175218', priv='Administrator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='CmdPOSTEvent — POST event notification (confirmed symbol)'),
    (0x2e, 0x07): DellEntry(name='(Group Extension)', priv='User', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='OEM/Group NetFn. First 3 bytes = IANA'),
    (0x2e, 0x08): DellEntry(name='(Group Extension)', priv='User', sessionless=True, handler_addr=None, live_status='?', not_present=False, description='OEM/Group NetFn command'),
    (0x2e, 0x21): DellEntry(name='0x00188484', priv='Administrator', sessionless=False, handler_addr=None, live_status='', not_present=False, description='Stub/not-implemented (shared handler)'),
    (0x2e, 0xcc): DellEntry(name='CmdOSAOEMCmdHandler', priv='Callback', sessionless=True, handler_addr=None, live_status='YES: 0xC7 (needs data)', not_present=False, description='OSA OEM command handler'),
    (0x30, 0x00): DellEntry(name='CmdOEMGetChassisCapabilities', priv='User', sessionless=False, handler_addr=409116, live_status='No (0xC1)', not_present=True, description='Dell OEM chassis info / blade identification — NOT accessible on LAN or KCS'),
    (0x30, 0x01): DellEntry(name='(MASER init area)', priv='User', sessionless=False, handler_addr=396176, live_status='No (0xC1)', not_present=True, description='MASER/OSA initialization — NOT accessible on LAN'),
    (0x30, 0x02): DellEntry(name='(OEM cmd)', priv='Operator', sessionless=False, handler_addr=1128068, live_status='No (0xC1)', not_present=True, description='Dell OEM command 0x02 — NOT accessible on LAN'),
    (0x30, 0x04): DellEntry(name='(near CmdOEMLockMASER)', priv='Operator', sessionless=True, handler_addr=409372, live_status='No (0xC1)', not_present=True, description='MASER lock NOT available on LAN — KCS-only or firewall-blocked'),
    (0x30, 0x05): DellEntry(name='CmdOEM Cmd 0x05', priv='Administrator', sessionless=True, handler_addr=409716, live_status='No (0xC1)', not_present=True, description='NOT accessible on LAN'),
    (0x30, 0x06): DellEntry(name='(OEM cmd)', priv='Operator', sessionless=True, handler_addr=408892, live_status='No (0xC1)', not_present=True, description='NOT accessible on LAN'),
    (0x30, 0x0a): DellEntry(name='(MASER area)', priv='User', sessionless=False, handler_addr=396520, live_status='No (0xC1)', not_present=True, description='MASER-area — NOT accessible on LAN'),
    (0x30, 0x18): DellEntry(name='CmdGetBladeID area', priv='User', sessionless=False, handler_addr=408316, live_status='No (0xC1)', not_present=True, description='NOT accessible on LAN'),
    (0x30, 0x1c): DellEntry(name='CmdOEMExtendedConfigure', priv='Administrator', sessionless=True, handler_addr=689028, live_status='Yes', not_present=False, description='LIVE: 0xC7 (needs 4+ bytes). racadm extended config reserve/access'),
    (0x30, 0x20): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=411704, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x21): DellEntry(name='(stub handler)', priv='Administrator', sessionless=False, handler_addr=1606788, live_status='—', not_present=False, description='LIVE: 0xC7. Stub 0x00188484 — accepts data but likely returns error'),
    (0x30, 0x22): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=810968, live_status='Yes', not_present=False, description='LIVE: returns empty (success)'),
    (0x30, 0x24): DellEntry(name='(OEM cmd)', priv='Administrator', sessionless=False, handler_addr=1612628, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x25): DellEntry(name='CmdOEMGetPwrCapEn?', priv='User', sessionless=False, handler_addr=1612836, live_status='Yes', not_present=False, description='LIVE: returns 00 (power capping disabled)'),
    (0x30, 0x26): DellEntry(name='CmdOEMResetPwrConsumptionDataCounters (near)', priv='Administrator', sessionless=False, handler_addr=384512, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x27): DellEntry(name='CmdOEMExtendedConfigure (get)', priv='Administrator', sessionless=True, handler_addr=685880, live_status='Yes', not_present=False, description='LIVE: returns data with 4 bytes input. 0x27 grp 0x00 0x00 0x00 → racadm config backend'),
    (0x30, 0x30): DellEntry(name='(OEM cmd)', priv='Administrator', sessionless=False, handler_addr=415380, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x31): DellEntry(name='(OEM cmd)', priv='Administrator', sessionless=True, handler_addr=415688, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x32): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=689816, live_status='Yes', not_present=False, description='LIVE: returns 00'),
    (0x30, 0x33): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=417628, live_status='Yes', not_present=False, description='LIVE: returns 01 00 01'),
    (0x30, 0x37): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=408048, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0x38): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=407916, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0x39): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=408180, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0x51): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=407156, live_status='Yes', not_present=False, description='LIVE: returns 03 00 00 00 00'),
    (0x30, 0x87): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=408476, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0x8b): DellEntry(name='CmdOEMCheckMASER_IPMIcmdStatus?', priv='Operator', sessionless=False, handler_addr=409852, live_status='Yes', not_present=False, description='LIVE: 0xC7 (needs >6 bytes)'),
    (0x30, 0x8c): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=412348, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0x8d): DellEntry(name='(OEM cmd)', priv='Operator', sessionless=False, handler_addr=412588, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x9c): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=417936, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0x9d): DellEntry(name='(OEM cmd)', priv='Operator', sessionless=False, handler_addr=418092, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xa0): DellEntry(name='CmdOEMGetMASERAccessState', priv='User', sessionless=False, handler_addr=1528604, live_status='Yes', not_present=False, description='LIVE: returns 00 (MASER unlocked/accessible)'),
    (0x30, 0xa1): DellEntry(name='CmdOEMUnLockMASER', priv='User', sessionless=True, handler_addr=503036, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session). Confirmed symbol match'),
    (0x30, 0xa2): DellEntry(name='CmdOEMvFlash / CmdOEMMASERPartitionAccess', priv='User', sessionless=True, handler_addr=457240, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session)'),
    (0x30, 0xa3): DellEntry(name='CmdOEMPOST* (near CmdOEMPOSTGetBootVolLabel)', priv='User', sessionless=True, handler_addr=472940, live_status='Yes', not_present=False, description='LIVE: 0xCC (data content wrong). Accessible on LAN but needs correct payload'),
    (0x30, 0xa4): DellEntry(name='CmdOEMPOST* (near CmdOEMPOSTSetBIOSPassword)', priv='User', sessionless=True, handler_addr=473568, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session)'),
    (0x30, 0xa5): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=1530444, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session)'),
    (0x30, 0xa6): DellEntry(name='CmdOEMPOSTMASERAccess (near)', priv='User', sessionless=True, handler_addr=474336, live_status='Yes', not_present=False, description='LIVE: 0xCC (data content wrong). Accessible on LAN'),
    (0x30, 0xa9): DellEntry(name='CmdOEMPOSTSetBIOSPassword (near)', priv='User', sessionless=True, handler_addr=469008, live_status='Yes', not_present=False, description='LIVE: rsp=0x03 (Dell-specific error). Accessible on LAN — NOT KCS-only as predicted!'),
    (0x30, 0xaa): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=463156, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session)'),
    (0x30, 0xab): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=464588, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xac): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=465528, live_status='Yes', not_present=False, description='LIVE: rsp=0x01 (no active MASER session)'),
    (0x30, 0xad): DellEntry(name='CmdOEMGetMASERType', priv='User', sessionless=True, handler_addr=464268, live_status='Yes', not_present=False, description='LIVE: returns 00 00 00 with 2-byte input. No SD card present'),
    (0x30, 0xae): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=463736, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xaf): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=464000, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xb0): DellEntry(name='CmdOEMPwrAvgInterval / CmdOEMPwrCapEn area', priv='User', sessionless=False, handler_addr=386820, live_status='Yes', not_present=False, description='LIVE: 0xC7 (needs >1 byte)'),
    (0x30, 0xb3): DellEntry(name='CmdOEMPwrAvgRange area', priv='User', sessionless=False, handler_addr=385928, live_status='Yes', not_present=False, description='LIVE: 0xC7 (needs >1 byte)'),
    (0x30, 0xb5): DellEntry(name='DellCmdGetLCDInfo', priv='User', sessionless=False, handler_addr=688140, live_status='Yes', not_present=False, description='LIVE: returns empty (success) with 0x00 0x00. LCD info param 0'),
    (0x30, 0xb6): DellEntry(name='CmdOEMPwrHeadroom area', priv='Operator', sessionless=False, handler_addr=390888, live_status='Yes', not_present=False, description='LIVE: 0xC7 (needs >1 byte)'),
    (0x30, 0xb7): DellEntry(name='CmdOEMGetPWRConsumptionData', priv='User', sessionless=False, handler_addr=391212, live_status='Yes', not_present=False, description='LIVE: returns 00 with 0x0A 0x00. Power consumption param 0x0A'),
    (0x30, 0xb8): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=418324, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xb9): DellEntry(name='(OEM cmd)', priv='Administrator', sessionless=False, handler_addr=418652, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xba): DellEntry(name='Power area', priv='User', sessionless=False, handler_addr=391432, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xbb): DellEntry(name='Power area', priv='User', sessionless=False, handler_addr=391676, live_status='Yes', not_present=False, description='LIVE: returns 0c 05 ca 04'),
    (0x30, 0xbc): DellEntry(name='(OEM cmd)', priv='Administrator', sessionless=True, handler_addr=419192, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xbe): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=419440, live_status='No (0xC1)', not_present=False, description='NOT PRESENT on LAN'),
    (0x30, 0xbf): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=419504, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xc0): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=734844, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xc1): DellEntry(name='(OEM cmd)', priv='Operator', sessionless=True, handler_addr=423476, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xc2): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=609268, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xc3): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=411376, live_status='Yes', not_present=False, description='LIVE: 0xCC (right length but wrong content)'),
    (0x30, 0xc4): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=734176, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xca): DellEntry(name='DelleKmsCmdHlder area', priv='Administrator', sessionless=True, handler_addr=1539360, live_status='Yes', not_present=False, description='LIVE: 0xC7→0xC1 at 6+ bytes. eKMS not enabled on this firmware'),
    (0x30, 0xcc): DellEntry(name='CmdOEMPowerConsumption area', priv='User', sessionless=False, handler_addr=388496, live_status='Yes', not_present=False, description='LIVE: 0xCC at 4 bytes (right length, wrong sub-cmd)'),
    (0x30, 0xcd): DellEntry(name='Power area', priv='User', sessionless=False, handler_addr=390664, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
    (0x30, 0xd0): DellEntry(name='CmdOEMDellFactory / MaserCmd area', priv='Administrator', sessionless=False, handler_addr=393700, live_status='Yes', not_present=False, description='LIVE: 0xC7. Reachable on LAN but needs correct payload'),
    (0x30, 0xd2): DellEntry(name='(OEM cmd)', priv='User', sessionless=True, handler_addr=1554480, live_status='Yes', not_present=False, description='LIVE: returns empty (success)'),
    (0x30, 0xd4): DellEntry(name='(OEM cmd)', priv='User', sessionless=False, handler_addr=394900, live_status='Yes', not_present=False, description='LIVE: 0xC7'),
}

# Convenience views.
DELL_NAMES: dict[tuple[int, int], str] = {
    k: v.name for k, v in DELL_DISPATCH.items() if v.name
}
DELL_SESSIONLESS: set[tuple[int, int]] = {
    k for k, v in DELL_DISPATCH.items() if v.sessionless
}
DELL_DISABLED: set[tuple[int, int]] = {
    k for k, v in DELL_DISPATCH.items() if v.not_present
}
