"""
zipmi.scapy_ipmi.oem.dell — Dell PowerEdge OEM commands (IANA 674).

WHAT     Names + a handful of decoded request/response payloads for Dell
         iDRAC OEM commands found in the wild. The full dispatch table
         (120 std + 93 OEM, as RE'd from iDRAC6 firmware) lives at
         /Volumes/yyy/phd/bmc/dell/fullfw-ipmi-commands.md; we cherry-
         pick the ones we've actually used in research.

WHY      Studying Dell iDRAC6 means we can immediately decode familiar
         attack-relevant commands (PROCHOT throttle, power cap,
         WSMAN-bypass-style boot config, sensor threshold tamper).

LOAD     `zipmi.load_vendor("dell")` from anywhere — mutates the OEM
         registry; subsequent fuzz / pcap dissection picks up the
         names.

REFS     /Volumes/yyy/phd/bmc/dell/fullfw-ipmi-commands.md
         /Volumes/yyy/phd/bmc/dell/dell-prochot-throttle-attack.md
         /Volumes/yyy/phd/bmc/dell/dell-thermal-bios-attack.md
"""

from __future__ import annotations

from scapy.fields import ByteEnumField, ByteField, XByteField
from scapy.packet import Packet

from ..commands import COMP_CODE
from ._registry import register


# --- decoded payloads ----------------------------------------------------

class DellPROCHOTThrottleReq(Packet):
    """Dell PROCHOT throttle (NetFn 0x30, Cmd 0xC0).

    Forces PROCHOT# assertion on the host CPU — instant CPU throttle.
    Reverse-engineered in /Volumes/yyy/phd/bmc/dell/dell-prochot-throttle-attack.md.
    """

    name = "Dell PROCHOT Throttle Request"
    fields_desc = [
        ByteField("subcommand", 0x00),       # 0x00 = enable, 0x01 = disable
    ]

    def extract_padding(self, s):
        return b"", s


class DellPROCHOTThrottleResp(Packet):
    name = "Dell PROCHOT Throttle Response"
    fields_desc = [ByteEnumField("comp_code", 0x00, COMP_CODE)]

    def extract_padding(self, s):
        return b"", s


class DellGetPowerCapReq(Packet):
    """Dell Get Power Cap Configuration (NetFn 0x30, Cmd 0xBA)."""

    name = "Dell Get Power Cap Request"
    fields_desc = [XByteField("selector", 0x00)]

    def extract_padding(self, s):
        return b"", s


# --- registration --------------------------------------------------------
#
# Cherry-picked for now. Codegen from fullfw-ipmi-commands.md to populate
# the rest is a follow-on (parsers/md_table.py).

DELL_IANA = 674


# Auto-generated dispatch table from
# /Volumes/yyy/phd/bmc/dell/fullfw-ipmi-commands.md (283 markdown rows
# parsed into 192 unique (NetFn, cmd) entries — 130 OEM 0x30, 14 0x2E
# group, plus 14 Dell-extended overrides of standard cmds).
from .dell_generated import DELL_DISPATCH, DELL_NAMES, DELL_DISABLED  # noqa: E402

# Binary-RE'd handler names — the canonical source. Replaces the
# placeholder "(FW phase cmd)" / "(OEM cmd)" / "(MASER init area)"
# entries that came from the human MD analysis. Generated by running
# radare2 on T710-bmc/bin/fullfw and reading the dispatch tables at
# 0x0019e238 (std) and 0x0019fac0 (OEM). See dell_binary_names.py
# header for regen instructions.
from .dell_binary_names import DELL_BINARY_NAMES  # noqa: E402

# Hand-curated overrides for cmds where empirical research (separate from
# the dispatch-table RE) renamed the function. These win over both the
# binary-RE names and the MD names. Currently:
#   (0x30, 0xC0) — binary names it CmdThrottleCPU; the PROCHOT attack
#                  vector docs use the more-specific "PROCHOTThrottle".
DELL_NAME_OVERRIDES = {
    (0x30, 0xC0): "Dell PROCHOTThrottle",
    (0x30, 0xB1): "Dell SetPowerCap",
    (0x30, 0xB2): "Dell GetPowerCap",
    (0x30, 0xBA): "Dell GetPowerCapConfig",
    (0x30, 0xE0): "Dell GetSensorThreshold",
    (0x30, 0xE1): "Dell SetSensorThreshold",
}

# Resolution order: hand-curated → binary-RE → MD-derived (DELL_NAMES).
DELL_CMD_NAMES = {
    **{k: f"Dell {v}" for k, v in DELL_NAMES.items()},
    **DELL_BINARY_NAMES,
    **DELL_NAME_OVERRIDES,
}


# Decoded payloads — currently only the two cmds we've actually used. The
# rest stay as raw send_raw passthroughs; their names + privilege come
# from DELL_DISPATCH so fuzz / pcap output is still annotated.
DELL_PAYLOADS = {
    (0x30, 0xC0): (DellPROCHOTThrottleReq, DellPROCHOTThrottleResp),
    (0x30, 0xBA): (DellGetPowerCapReq, None),
}


register("dell", DELL_IANA, DELL_CMD_NAMES, DELL_PAYLOADS)
