"""zipmi.scapy_ipmi.oem.idrac9_known_context — full iDRAC9 audit overlay.

Hand-curated entries from full audit of every iDRAC9 OEM cmd plus
the std-IPMI cmds iDRAC9 ships handlers for. Sources:
  - ~/phd/bmc/idrac9-firmware/IPMI_COMMAND_ENUMERATION.md
  - ~/phd/bmc/idrac9-firmware/idrac9-dispatch-tables.md
  - addr-resolved + R_ARM_GLOB_DAT runtime-dispatch RE
  - iDRAC6 audit cross-reference (carried-over cmds)

Risk markers (in summary):
  *      interesting / non-obvious behaviour
  **     sensitive (admin escalation surface)
  ***    destructive / critical (data loss, brick, host attack)

Reservation flows: SDR (0x0A 0x22), SEL (0x0A 0x42), Dell
ResvExtendedConfigure (0x2E 0x01).
"""

KNOWN_CONTEXT: dict[tuple, dict] = {
    (0, 0): {'summary': 'Get Chassis Capabilities. Returns 6 bytes: cap flags + 4 IPMB addresses.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChassisCapabilities'},
    (0, 1): {'summary': 'Get Chassis Status. Returns power state, last-power-event cause, misc state.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChassisStatus'},
    (0, 2): {'summary': '★ Chassis Control (down/up/cycle/reset/diag-int/soft).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ChassisControl'},
    (0, 4): {'summary': 'Chassis Identify. Blinks the front-panel UID LED.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ChassisIdentify'},
    (0, 5): {'summary': '★ Set Chassis Capabilities — admin-only.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetChassisCapabilities'},
    (0, 6): {'summary': '★ Set Power Restore Policy. iDRAC9 OEM override (0x30 0x06 also exists).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetPowerRestorePolicy'},
    (0, 7): {'summary': 'Get System Restart Cause.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSystemRestartCause'},
    (0, 8): {'summary': '★★ Set System Boot Options. Pin BIOS boot device + flags.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSystemBootOptions'},
    (0, 9): {'summary': 'Get System Boot Options.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSystemBootOptions'},
    (0, 10): {'summary': '★ Set Front Panel Button Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetFrontPanelButtonEnables'},
    (0, 11): {'summary': 'Set Power Cycle Interval.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetPowerCycleInterval'},
    (4, 0): {'summary': 'Set Event Receiver.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetEventReceiver'},
    (4, 1): {'summary': 'Get Event Receiver.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetEventReceiver'},
    (4, 2): {'summary': '★ Platform Event Message — SEL injection.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'PlatformEvent'},
    (4, 16): {'summary': 'PEF Get Capabilities.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetPEFCapabilities'},
    (4, 17): {'summary': 'PEF Arm Postpone Timer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ArmPEFPostponeTimer'},
    (4, 18): {'summary': '★★ DellOEMCmdSetPEF — write PEF config (filters/policies/SNMP-trap dest).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetPEFConfigurationParameters'},
    (4, 19): {'summary': 'DellOEMCmdGetPEF — read PEF config.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetPEFConfigurationParameters'},
    (4, 20): {'summary': 'PEF Set Last Processed Event ID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetLastProcessedEventID'},
    (4, 21): {'summary': 'PEF Get Last Processed Event ID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetLastProcessedEventID'},
    (4, 22): {'summary': '★ PEF Alert Immediate.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'AlertImmediate'},
    (4, 23): {'summary': 'PETC Acknowledge.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'PETAcknowledge'},
    (4, 35): {'summary': 'Get Sensor Reading Factors.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorReadingFactors'},
    (4, 36): {'summary': '★★ Set Sensor Hysteresis.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSensorHysteresis'},
    (4, 37): {'summary': 'Get Sensor Hysteresis.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorHysteresis'},
    (4, 38): {'summary': '★★★ Set Sensor Thresholds / SetSensorThresholdsOverride. **CRITICAL — raise thermal-shutdown threshold to defeat protective shutdowns during a thermal/load attack.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSensorThreshold'},
    (4, 39): {'summary': 'Get Sensor Thresholds.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorThreshold'},
    (4, 40): {'summary': 'Set Sensor Event Enable.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSensorEventEnable'},
    (4, 41): {'summary': 'Get Sensor Event Enable.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorEventEnable'},
    (4, 42): {'summary': 'Re-arm Sensor Events.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ReArmSensorEvents'},
    (4, 43): {'summary': 'Get Sensor Event Status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorEventStatus'},
    (4, 45): {'summary': 'Get Sensor Reading.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorReading'},
    (4, 47): {'summary': 'Get Sensor Type.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSensorType'},
    (4, 48): {'summary': '★ Set Sensor Reading. iDRAC9 allows admin push (synthetic readings).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSensorReadingAndEventStatus'},
    (4, 64): {'summary': '★ iDRAC9 Sensor Test (libmaser/test handler).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SensorTest'},
    (6, 1): {'summary': 'Get Device ID. Returns Dell mfg ID 674, product, fw rev, IPMI ver.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetDeviceID'},
    (6, 2): {'summary': '★★ Cold Reset (BMC reboot).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ColdReset'},
    (6, 3): {'summary': 'Warm Reset.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'WarmReset'},
    (6, 4): {'summary': 'Get Self Test Results.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSelfTestResults'},
    (6, 5): {'summary': '★★★ CmdManufacturingTestOn. **Unlocks factory test mode — hidden cmds + weakened auth. DO NOT run on production iDRAC9.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ManufacturingTestOn'},
    (6, 6): {'summary': 'Set ACPI Power State.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetACPIPowerState'},
    (6, 7): {'summary': 'Get ACPI Power State.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetACPIPowerState'},
    (6, 8): {'summary': 'Get Device GUID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetDeviceGUID'},
    (6, 9): {'summary': 'Get NetFn Support.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetNetFnSupport'},
    (6, 10): {'summary': 'Get Command Support.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetCommandSupport'},
    (6, 11): {'summary': 'Get Command Sub-function Support.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetCommandSubFunctionSupport'},
    (6, 12): {'summary': 'Get Configurable Commands.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetConfigurableCommands'},
    (6, 13): {'summary': 'Get Configurable Command Sub-functions.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetConfigurableCommandSubFunctions'},
    (6, 34): {'summary': 'Reset Watchdog Timer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ResetWatchdogTimer'},
    (6, 36): {'summary': '★ Set Watchdog Timer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetWatchdogTimer'},
    (6, 37): {'summary': 'Get Watchdog Timer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetWatchdogTimer'},
    (6, 46): {'summary': 'Set BMC Global Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetBMCGlobalEnables'},
    (6, 47): {'summary': 'Get BMC Global Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetBMCGlobalEnables'},
    (6, 48): {'summary': 'Clear Message Flags.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ClearMessageFlags'},
    (6, 49): {'summary': 'Get Message Flags.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetMessageFlags'},
    (6, 50): {'summary': 'Enable Message Channel Receive.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'EnableMessageChannelReceive'},
    (6, 51): {'summary': 'Get Message.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetMessage'},
    (6, 52): {'summary': '★ Send Message — IPMB bridging primitive.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SendMessage'},
    (6, 53): {'summary': 'Read Event Message Buffer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ReadEventMessageBuffer'},
    (6, 55): {'summary': 'Get System GUID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSystemGUID'},
    (6, 56): {'summary': 'Get Channel Auth Capabilities.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelAuthenticationCapabilities'},
    (6, 57): {'summary': 'Get Session Challenge.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSessionChallenge'},
    (6, 58): {'summary': 'Activate Session.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ActivateSession'},
    (6, 59): {'summary': 'Set Session Privilege Level.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSessionPrivilegeLevel'},
    (6, 60): {'summary': 'Close Session.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CloseSession'},
    (6, 61): {'summary': 'Get Session Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSessionInfo'},
    (6, 63): {'summary': 'Get AuthCode.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetAuthCode'},
    (6, 64): {'summary': '★★ Set Channel Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetChannelAccess'},
    (6, 65): {'summary': 'Get Channel Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelAccess'},
    (6, 66): {'summary': 'Get Channel Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelInfo'},
    (6, 67): {'summary': '★★ Set User Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetUserAccess'},
    (6, 68): {'summary': 'Get User Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetUserAccess'},
    (6, 69): {'summary': '★★ Set User Name.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetUserName'},
    (6, 70): {'summary': 'Get User Name.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetUserName'},
    (6, 71): {'summary': '★★★ Set User Password — **OEM password change path; sub-byte 0x02 sets cleartext password**.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetUserPassword'},
    (6, 72): {'summary': 'Activate Payload (SOL).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ActivatePayload'},
    (6, 73): {'summary': 'Deactivate Payload.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DeactivatePayload'},
    (6, 74): {'summary': 'Get Payload Activation Status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetPayloadActivationStatus'},
    (6, 75): {'summary': 'Get Payload Instance Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetPayloadInstanceInfo'},
    (6, 76): {'summary': 'Set User Payload Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetUserPayloadAccess'},
    (6, 77): {'summary': 'Get User Payload Access.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetUserPayloadAccess'},
    (6, 78): {'summary': 'Get Channel Payload Support.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelPayloadSupport'},
    (6, 79): {'summary': 'Get Channel Payload Version.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelPayloadVersion'},
    (6, 80): {'summary': 'Get Channel OEM Payload Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelOEMPayloadInfo'},
    (6, 82): {'summary': '★★★ CmdMasterWR (Master Write-Read I2C). **Direct I2C bus access from BMC — VRMs, SPDs, CPLD, PMBus PSUs.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'MasterWriteRead'},
    (6, 84): {'summary': 'Get Channel Cipher Suites.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetChannelCipherSuites'},
    (6, 85): {'summary': 'Suspend/Resume Payload Encryption.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SuspendResumePayloadEncryption'},
    (6, 86): {'summary': '★★ Set Channel Security Keys (K_R / K_G).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetChannelSecurityKeys'},
    (6, 87): {'summary': 'Get System Interface Capabilities.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSystemInterfaceCapabilities'},
    (6, 96): {'summary': 'Set Command Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetCommandEnables'},
    (6, 97): {'summary': 'Get Command Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetCommandEnables'},
    (6, 98): {'summary': 'Set Command Sub-function Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetCommandSubFunctionEnables'},
    (6, 99): {'summary': 'Get Command Sub-function Enables.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetCommandSubFunctionEnables'},
    (6, 100): {'summary': 'Get OEM NetFn IANA Support.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetOEMNetFnIANASupport'},
    (8, 2): {'summary': '★★★ CmdFirmwareUpdate (iDRAC9 fw update kickoff). Wrong image → BMC brick.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdFirmwareUpdate'},
    (8, 16): {'summary': '★★★ CmdFirmwareUpdatePhase1.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdFirmwareUpdatePhase1'},
    (8, 17): {'summary': '★★★ CmdFirmwareUpdatePhase2.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdFirmwareUpdatePhase2'},
    (8, 18): {'summary': 'CmdGetFirmwareUpdateStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdGetFirmwareUpdateStatus'},
    (8, 19): {'summary': 'CmdGetFirmwareVersion.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdGetFirmwareVersion'},
    (8, 20): {'summary': '★★ CmdRollbackFirmwareVersion.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdRollbackFirmwareVersion'},
    (8, 21): {'summary': '★ CmdCancelFirmwareUpdate.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdCancelFirmwareUpdate'},
    (8, 22): {'summary': '★★ CmdSetFWImageStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdSetFWImageStatus'},
    (10, 16): {'summary': 'Get FRU Inventory Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetFRUInventoryAreaInfo'},
    (10, 17): {'summary': 'Read FRU Data.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ReadFRUData'},
    (10, 18): {'summary': '★★ Write FRU Data.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'WriteFRUData'},
    (10, 32): {'summary': 'Get SDR Repository Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSDRRepositoryInfo'},
    (10, 34): {'summary': 'CmdResvSDRRepo: returns 2-byte reservation ID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ReserveSDRRepository'},
    (10, 35): {'summary': 'Get SDR.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSDR', 'reservation_from': 'CmdResvSDRRepo (0x0A 0x22) returns the reservation ID'},
    (10, 37): {'summary': 'Partial Add SDR.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'PartialAddSDR'},
    (10, 38): {'reservation_from': 'CmdResvSDRRepo (0x0A 0x22) returns the reservation ID', 'name': 'DeleteSDR'},
    (10, 39): {'summary': '★★ Clear SDR Repository.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ClearSDRRepository'},
    (10, 40): {'summary': 'Get SDR Repository Time.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSDRRepositoryTime'},
    (10, 41): {'summary': 'Set SDR Repository Time.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSDRRepositoryTime'},
    (10, 44): {'summary': 'Run Initialization Agent.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'RunInitializationAgent'},
    (10, 64): {'summary': 'Get SEL Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSELInfo'},
    (10, 66): {'summary': 'CmdReserveSEL: returns 2-byte reservation ID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ReserveSEL'},
    (10, 67): {'summary': 'Get SEL Entry.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSELEntry'},
    (10, 68): {'summary': '★ Add SEL Entry.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'AddSELEntry'},
    (10, 70): {'reservation_from': 'CmdReserveSEL (0x0A 0x42) returns the reservation ID', 'name': 'DeleteSELEntry'},
    (10, 71): {'summary': '★★ Clear SEL — log cleanup primitive.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'ClearSEL'},
    (10, 72): {'summary': 'Get SEL Time.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSELTime'},
    (10, 73): {'summary': '★ Set SEL Time — timestamp skew.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSELTime'},
    (12, 1): {'summary': '★★ DellCmdSetLANConfigParam.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetLANConfigurationParameters'},
    (12, 2): {'summary': 'DellCmdGetLANConfigParam.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetLANConfigurationParameters'},
    (12, 16): {'summary': '★★ DellCmdSetSerModemConfigParam.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSerialModemConfiguration'},
    (12, 17): {'summary': 'DellCmdGetSerModemConfigParam.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSerialModemConfiguration'},
    (12, 33): {'summary': '★★ DellCmdSetSOLConfiguration.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetSOLConfigurationParameters'},
    (12, 34): {'summary': 'DellCmdGetSOLConfiguration.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetSOLConfigurationParameters'},
    (44, 1): {'summary': 'DCMI Get DCMI Capabilities Info (group extension 0xDC).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetDCMICapabilitiesInfo'},
    (44, 2): {'summary': 'DCMI Get Power Reading.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetPowerReading'},
    (44, 3): {'summary': 'DCMI Get Power Limit.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetPowerLimit'},
    (44, 4): {'summary': '★★ DCMI Set Power Limit.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMISetPowerLimit'},
    (44, 5): {'summary': '★ DCMI Activate/Deactivate Power Limit.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIActivate/DeactivatePowerLimit'},
    (44, 6): {'summary': 'DCMI Get Asset Tag.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetAssetTag'},
    (44, 7): {'summary': 'DCMI Get DCMI Sensor Info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetDCMISensorInfo'},
    (44, 8): {'summary': '★ DCMI Set Asset Tag.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMISetAssetTag'},
    (44, 9): {'summary': 'DCMI Get MC ID String.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetMCIDString'},
    (44, 10): {'summary': '★ DCMI Set MC ID String.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMISetMCIDString'},
    (44, 11): {'summary': '★★ DCMI Set Thermal Limit.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMISetThermalLimit'},
    (44, 12): {'summary': 'DCMI Get Thermal Limit.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetThermalLimit'},
    (44, 16): {'summary': 'DCMI Get Temperature Readings.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetTemperatureReadings'},
    (44, 18): {'summary': '★★ DCMI Set DCMI Configuration Parameters.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMISetDCMIConfigurationParameters'},
    (44, 19): {'summary': 'DCMI Get DCMI Configuration Parameters.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DCMIGetDCMIConfigurationParameters'},
    (46, 1): {'summary': 'CmdResvExtendedConfigure: returns reservation ID for Get/Set ExtendedConfigure flow. IANA prefix 0xa2 0x02 0x00 mandatory.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdResvExtendedConfigure'},
    (46, 2): {'summary': 'CmdGetExtendedConfigure: read Dell internal config var. Needs reservationID from 0x2E 0x01.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdGetExtendedConfigure', 'reservation_from': 'CmdResvExtendedConfigure (0x2E 0x01) returns the reservation ID. Without it: CC=0xC5.'},
    (46, 3): {'summary': '★★ CmdSetExtendedConfigure: WRITE Dell internal config. Modifies BMC settings outside std spec — racadm uses this.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdSetExtendedConfigure', 'reservation_from': 'CmdResvExtendedConfigure (0x2E 0x01) returns the reservation ID. Without it: CC=0xC5.'},
    (46, 4): {'summary': 'CmdPOSTEvent.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdPOSTEvent'},
    (46, 33): {'summary': 'CmdResetToDefault: stub handler.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdResetToDefaultStub'},
    (46, 64): {'summary': '★★★ sendRawPECI: direct PECI passthrough to host CPU. **Read MSRs (incl. SGX), CR registers, dump SMRAM control state. Most powerful primitive in Intel Node Manager (NM).**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'sendRawPECI'},
    (46, 65): {'summary': '★ Intel NM extended cmd (RE pending — table slot allocated, runtime-bound stub).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 66): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 67): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 68): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 69): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 70): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 75): {'summary': '★ getCPUandMemoryTemperature: live CPU/DIMM junction temps via PECI.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getCPUandMemoryTemperature'},
    (46, 96): {'summary': '★ Intel NM cmd (RE pending — likely thermal/power telemetry).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 97): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 100): {'summary': 'getCUPSCapabilities: what CUPS (Compute Usage per Second) features supported.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getCUPSCapabilities'},
    (46, 101): {'summary': 'getCUPSData: live core/IO/mem-bandwidth %.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getCUPSData'},
    (46, 102): {'summary': '★ setCUPSConfig: sample period, IIO bandwidth thresholds.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setCUPSConfig'},
    (46, 103): {'summary': 'getCUPSConfig.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getCUPSConfig'},
    (46, 104): {'summary': '★ setCUPSPolicy: per-CPU CUPS thresholds.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setCUPSPolicy'},
    (46, 105): {'summary': 'getCUPSPolicy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getCUPSPolicy'},
    (46, 128): {'summary': 'getBootGuardVersion: Intel Boot Guard fw version.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getBootGuardVersion'},
    (46, 129): {'summary': 'getBootGuardCapability: Boot Guard mode (Verified / Measured / Both).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getBootGuardCapability'},
    (46, 130): {'summary': '★ getBootGuardHealth: tick count of Boot Guard verification failures. Trust-state probe.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getBootGuardHealth'},
    (46, 168): {'summary': 'Dual-dispatch: getImageInventory (Intel ME fw-image manifest, Intel IANA prefix) OR ★★ CmdOEMSupportAssist admin-priv path (Dell IANA — runtime-routed). See ~/phd/bmc/dell/idrac-supportassist-export.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DualDispatch'},
    (46, 183): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 186): {'summary': '★ Intel NM extended cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMExtendedCmd'},
    (46, 192): {'summary': '★★ enableDisableNodeManagerPolicyControl: master toggle for Node Manager policies.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'enableDisableNodeManagerPolicyControl'},
    (46, 193): {'summary': '★★★ setNodeManagerPolicy: power-cap config (W, correction time, trigger limit, statistics period). **Silent DoS — drop server into 50W cap; CPU runs but slowly.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setNodeManagerPolicy'},
    (46, 194): {'summary': 'getNodeManagerPolicy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerPolicy'},
    (46, 195): {'summary': '★ setNodeManagerAlertThresholds.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setNodeManagerAlertThresholds'},
    (46, 196): {'summary': 'getNodeManagerAlertThresholds.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerAlertThresholds'},
    (46, 197): {'summary': '★ setNodeManagerPolicySuspendPeriods: time-of-day suspend windows.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setNodeManagerPolicySuspendPeriods'},
    (46, 198): {'summary': 'getNodeManagerPolicySuspendPeriods.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerPolicySuspendPeriods'},
    (46, 199): {'summary': '★ resetNodeManagerStatistics: zero stats per (mode, domain, policy). Forensic-evasion if power side-channel attack used.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'resetNodeManagerStatistics'},
    (46, 200): {'summary': 'getNodeManagerStatistics: avg/min/max/curr power, throttle dwell time.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerStatistics'},
    (46, 201): {'summary': 'getNodeManagerCapabilities.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerCapabilities'},
    (46, 202): {'summary': 'getNodeManagerVersion: Node Manager / ME firmware version.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerVersion'},
    (46, 203): {'summary': '★★ setNodeManagerPowerDrawRange: min/max per-domain power-draw (W). Bound the policy authority.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setNodeManagerPowerDrawRange'},
    (46, 204): {'summary': '★★★ CmdOSAOEMCmdHandler: Avocent OSA dispatcher (IANA 11102 prefix 0x5E 0x2B 0x00 — NOT Dell IANA). 9 sub-cmds: GetFWVersion/ID, SensorTest, **SetSysGUID**, **SetBMCSA**, **CmdResetToDefaultOSA** (alt factory-reset DESTRUCTIVE). Full writeup: ~/phd/bmc/dell/dell-cmd-deep-dives.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOSAOEMCmdHandler'},
    (46, 206): {'summary': '★ setNodeManagerAlertDestination: SNMP/PEF alert dest.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setNodeManagerAlertDestination'},
    (46, 207): {'summary': 'getNodeManagerAlertDestination.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNodeManagerAlertDestination'},
    (46, 208): {'summary': '★★ setTotalPowerBudgetRequest: rack/chassis-level total power cap.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setTotalPowerBudgetRequest'},
    (46, 209): {'summary': 'getTotalPowerBudgetRequest.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getTotalPowerBudgetRequest'},
    (46, 210): {'summary': '★★★ setMaxAllowedCPUCoresState / setMaxAllowedCPU_P_T_State: cap online cores OR cap CPU P-state / T-state. **Silent DoS — restrict to 1 P-state.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SetMaxAllowedCPUCoresState/SetMaxAllowedCPU_P_T_State'},
    (46, 211): {'summary': 'getMaxAllowedCPUCores / getMaxAllowedCPU_P_T_State.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetMaxAllowedCPUCores/GetMaxAllowedCPU_P_T_State'},
    (46, 212): {'summary': 'getNumberOf_P_T_StateRequest: pending P/T-state cap requests.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getNumberOf_P_T_StateRequest'},
    (46, 215): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 216): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 217): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 220): {'summary': '★★ setMEPowerState: force ME into specified power state (S0/S1/S5).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'setMEPowerState'},
    (46, 223): {'summary': '★★★ forceMERecovery: flip ME into recovery mode. **Post-exploit reset / unwedge tampered ME.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'forceMERecovery'},
    (46, 224): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 225): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 234): {'summary': 'getHostCPUData: read CPU vendor/family/stepping/capabilities via ME.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'getHostCPUData'},
    (46, 240): {'summary': '★ Intel NM cmd (RE pending — 0xF0-0xF6 likely factory/manufacturing).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 241): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 242): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 243): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 244): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 245): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (46, 246): {'summary': '★ Intel NM cmd (RE pending).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'IntelNMCmd'},
    (48, 0): {'summary': 'CmdOEMGetChassisCapabilities (iDRAC9 OEM override).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMGetChassisCapabilities'},
    (48, 1): {'summary': 'DellCmdGetChassisStatus (iDRAC9 OEM override).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetChassisStatus'},
    (48, 2): {'summary': 'DellCmdChassisControl (iDRAC9 OEM override).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdChassisControl'},
    (48, 4): {'summary': 'CmdOEMChassisIdentify.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMChassisIdentify'},
    (48, 5): {'summary': '★ CmdOEMSetChassisCapabilities.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSetChassisCapabilities'},
    (48, 6): {'summary': 'Set Power Restore Policy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellSetPowerRestorePolicy'},
    (48, 8): {'summary': 'OEMCmdSetSystemBootOptions (iDRAC9 OEM override of 0x00 0x08).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'OEMCmdSetSystemBootOptions'},
    (48, 10): {'summary': 'DellCmdSetFrntPanelState.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdSetFrntPanelState'},
    (48, 17): {'summary': '★ DellDCSSetChassisConfig: write modular-chassis config.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassisConfig'},
    (48, 18): {'summary': 'DellDCSGetChassisConfig: read modular-chassis config.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassisConfig'},
    (48, 19): {'summary': '★ DellDCSSetChassisName: rename the chassis.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassisName'},
    (48, 20): {'summary': 'DellDCSGetChassisName.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassisName'},
    (48, 21): {'summary': '★ DellDCSSetSensorInfo: push sensor metadata into the chassis CMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetSensorInfo'},
    (48, 22): {'summary': 'DellDCSGetSensorInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetSensorInfo'},
    (48, 23): {'summary': '★★ DellDCSSetChassisEncPwrCpng: write chassis-encoded power capping policy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassisEncPwrCpng'},
    (48, 24): {'summary': 'DellCmdGetBladeSlotId / CmdGetBladeID.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetBladeSlotId/CmdGetBladeID'},
    (48, 25): {'summary': '★ DellDCSSetFanSpeedCtrl: chassis fan-speed control mode.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetFanSpeedCtrl'},
    (48, 26): {'summary': 'DellDCSGetFanSpeedCtrl.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetFanSpeedCtrl'},
    (48, 27): {'summary': '★ DellDCSSetChassisLEDStatus: drive chassis-level LEDs.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassisLEDStatus'},
    (48, 28): {'summary': '★★★ DellCmdReadWriteLCD — front-panel LCD social-engineering primitive.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdReadWriteLCD'},
    (48, 29): {'summary': '★ DellDCSSetHDDInfo: push HDD inventory to CMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetHDDInfo'},
    (48, 30): {'summary': '★ DellDCSSetPSUInfo: push PSU inventory to CMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetPSUInfo'},
    (48, 31): {'summary': 'DellDCSGetPSUInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetPSUInfo'},
    (48, 32): {'summary': '★★ DellDCSSetChassisServiceTag: write chassis service tag (rebrand primitive).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassisServiceTag'},
    (48, 33): {'summary': '★★★ CmdResetToDefault: factory-default the BMC. **DESTRUCTIVE.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdResetToDefault'},
    (48, 34): {'summary': '★ DellDCSSetEnergyStorage: chassis backup-power state.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetEnergyStorage'},
    (48, 35): {'summary': 'DellDCSGetEnergyStorage.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetEnergyStorage'},
    (48, 37): {'summary': 'DellDCSGetChassisServiceTag.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassisServiceTag'},
    (48, 40): {'summary': '★ CmdSetNICSelectionFailover: NIC failover / teaming policy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdSetNICSelectionFailover'},
    (48, 41): {'summary': 'CmdGetNICSelectionFailover.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdGetNICSelectionFailover'},
    (48, 42): {'summary': '★★ DellDCSSetThermalThrtl: chassis-level thermal throttling policy.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetThermalThrtl'},
    (48, 43): {'summary': 'DellDCSGetThermalThrtl.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetThermalThrtl'},
    (48, 44): {'summary': 'DellDCSGetBMCs_SC_BMC_ProtocolVer: BMC↔SC (System Controller) protocol ver.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetBMCs_SC_BMC_ProtocolVer'},
    (48, 45): {'summary': 'DellDCSGetSCs_SC_BMC_ProtocolVer.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetSCs_SC_BMC_ProtocolVer'},
    (48, 46): {'summary': 'DellDCSGetChassPwrReadings.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassPwrReadings'},
    (48, 47): {'summary': '★ DellDCSSetChassPwrReadings: push synthetic chassis power readings into CMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetChassPwrReadings'},
    (48, 51): {'summary': 'Dell QueryGetCPLDRevision.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'QueryGetCPLDRevision'},
    (48, 53): {'summary': "★ Fresh Air: enable/query Dell 'Fresh Air' high-temp operating mode (relaxes thermal limits).", 'source': 'iDRAC9 RE doc + Dell', 'name': 'FreshAir'},
    (48, 54): {'summary': 'Dell PCIe SSDFRU.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'PCIeSSDFRU'},
    (48, 68): {'summary': 'DellDCSGetPCIEInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetPCIEInfo'},
    (48, 72): {'summary': '★★ DellDCSResetPeripheralDeviceController: reset a peripheral controller.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSResetPeripheralDeviceController'},
    (48, 73): {'summary': 'DellDCSGetResetPeripheralDeviceController: status of above.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetResetPeripheralDeviceController'},
    (48, 74): {'summary': 'DellDCSSyncPeripheralDeviceControllerResetStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSyncPeripheralDeviceControllerResetStatus'},
    (48, 75): {'summary': 'DellDCSGetPeripheralDeviceControllerResetStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetPeripheralDeviceControllerResetStatus'},
    (48, 76): {'summary': '★ DellDCSSetSecondPSUInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetSecondPSUInfo'},
    (48, 77): {'summary': 'DellDCSGetSecondPSUInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetSecondPSUInfo'},
    (48, 81): {'summary': 'DellCmdGetHostEventStatus: live host-side event status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetHostEventStatus'},
    (48, 135): {'summary': 'DellCmdServerPwrOnResponse: power-on response handshake.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdServerPwrOnResponse'},
    (48, 140): {'summary': 'DellCmdRequestedAirflow.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdRequestedAirflow'},
    (48, 141): {'summary': 'DellCmdVKVMStatus: virtual KVM session status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdVKVMStatus'},
    (48, 142): {'summary': 'DellCmdVMediaStatus: virtual-media mount status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdVMediaStatus'},
    (48, 143): {'summary': 'DellCmdServerPwrConsumption.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdServerPwrConsumption'},
    (48, 144): {'summary': 'DellCmdGetIMCStatusRegister: read IMC (Integrated Management Controller) status reg.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetIMCStatusRegister'},
    (48, 145): {'summary': '★ DellCmdIMCFirmwareUpdate: validator/handshake stub at 0x446589f4 in libmodular.so. Checks request byte0 high-nibble==7 + byte7==0x25 (magic matches dispatch flags). **NOT a fw write — returns CC=0 or 0xC1/0xC7. Real BMC fw-update path is host-side via Redfish/RACADM/DUP, not via IPMI LAN.** Full writeup: ~/phd/bmc/dell/idrac-imc-firmware-update.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdIMCFirmwareUpdate'},
    (48, 146): {'summary': 'DellCmdEDIDInfo: read display EDID via virtual-KVM path.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdEDIDInfo'},
    (48, 147): {'summary': 'DellCmdLCDReadFromStaging: LCD-staging-area read.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdLCDReadFromStaging'},
    (48, 148): {'summary': 'DellCmdLCDReadFromQueue: LCD-queue read.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdLCDReadFromQueue'},
    (48, 149): {'summary': '★ DellCmdChassisFanStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdChassisFanStatus'},
    (48, 150): {'summary': '★ DellCmdLoginAccess: login-state access query.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdLoginAccess'},
    (48, 151): {'summary': '★★ DellCmdSetIMCStatusRegister: WRITE IMC status reg.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdSetIMCStatusRegister'},
    (48, 152): {'summary': 'DellCmdLEDStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdLEDStatus'},
    (48, 153): {'summary': '★ DellCmdGetLastPostCode: read last-seen BIOS POST code.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetLastPostCode'},
    (48, 154): {'summary': '★★ DellCmdMemThrottlingCtrl: memory throttling control.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdMemThrottlingCtrl'},
    (48, 155): {'summary': 'DellCmdGetPowerCycleInterval.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetPowerCycleInterval'},
    (48, 158): {'summary': '★★ DellCmdBladeACPowerCycle: blade AC power cycle.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdBladeACPowerCycle'},
    (48, 159): {'summary': '★★★ DellCmdSpecialACCycle: special AC-cycle (deeper than std power cycle — may discharge caps, full-power-rail-cycle).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdSpecialACCycle'},
    (48, 160): {'summary': 'Get Soft Lock Status — Dell config-write-protect mode.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'Get'},
    (48, 161): {'summary': '★ CmdOEMPOSTMASERAccess: MASER access during host-POST.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMPOSTMASERAccess'},
    (48, 162): {'summary': '★★★ CmdOEMMASERPartitionAccess: direct R/W to MASER eMMC partitions. **HOST-ONLY (KCS-gated; same trust-boundary as BackupRestore — ANTI-LAN, NOT anti-host-root).** 26+ worker functions: Attach/Detach/ChangeAccessType, Create/Delete dynamic partitions, SECUPD multi-step authenticated write, LCLWipe (★★★ anti-forensic), Set/GetUEFIFlag (★★ boot-mode toggle). Sub-byte switch on byte 8 (range 0x00-0x27). Full writeup: ~/phd/bmc/dell/idrac-maser-partition-access.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMMASERPartitionAccess'},
    (48, 163): {'summary': 'CmdOEMRemoteEnablement: zero-touch provisioning.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMRemoteEnablement'},
    (48, 164): {'summary': 'CmdOEMvFlash.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMvFlash'},
    (48, 165): {'summary': '★★★ CmdOEMDellFactory: factory provisioning. DESTRUCTIVE.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMDellFactory'},
    (48, 166): {'summary': "★★★ CmdOEMBackupRestore: BMC NVRAM backup/restore dispatcher. **HOST-ONLY (IsMsgFromSystemInterface gate — LAN can't reach).** Sub-cmds 0x00-0x0B select operation (Populate/Send Backup, Populate/Send Restore, Query/Cancel/SetJobStatus). Backup blobs land on MASER eMMC. Restore replays user table + SSL certs + network cfg + RMCP+ keys — backdoor-staging primitive that survives all reset levels. Full writeup: ~/phd/bmc/dell/idrac-backuprestore-jstore.md.", 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBackupRestore'},
    (48, 166, 0): {'summary': 'CmdOEMBnRPopulateBackupCmd: stage Backup job spec.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRPopulateBackupCmd'},
    (48, 166, 1): {'summary': '★★ CmdOEMBnRSendBackupCmd: kick off backup → write config snapshot to MASER eMMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRSendBackupCmd'},
    (48, 166, 2): {'summary': 'CmdOEMBnRPopulateRestoreCmd: stage Restore job spec.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRPopulateRestoreCmd'},
    (48, 166, 3): {'summary': '★★★ CmdOEMBnRSendRestoreCmd: kick off restore — replays staged config (users, SSL, network, RMCP+ keys). **Backdoor-replay primitive.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRSendRestoreCmd'},
    (48, 166, 4): {'summary': 'CmdOEMBnRQueryJobStatus: poll backup/restore job status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRQueryJobStatus'},
    (48, 166, 5): {'summary': 'CmdOEMBnRQueryJobID: get job ID of pending backup/restore.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRQueryJobID'},
    (48, 166, 6): {'summary': '★ CmdOEMBnRCancelCmd: cancel pending backup/restore (User-priv → DoS primitive against legit backup job).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRCancelCmd'},
    (48, 166, 7): {'summary': '★★ CmdOEMBnRSetJobStatusCmd: write into job state machine. **Job-status-forgery candidate — RE pending priv-check confirmation.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRSetJobStatusCmd'},
    (48, 166, 10): {'summary': 'CmdOEMBnRGetAutoFeatureStatus: get auto-backup feature state.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMBnRGetAutoFeatureStatus'},
    (48, 167): {'summary': '★★★ CmdOEMToolSet: Dell ToolSet OEM dispatcher. **Embeds System Erase (full platform wipe — drives, BIOS NVRAM, certs, iDRAC config, LCL).** 9 sub-workers: Begin/Update/End-Marker, ExposeExecs/HideExecs (mount Dell-internal binaries to host), CollectData, GetDataInfo/GetStatus, **TSSystemErase** ★★★. HOST-ONLY KCS gate (anti-LAN, NOT anti-host-root). Full writeup: ~/phd/bmc/dell/idrac-toolset-systemerase.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMToolSet'},
    (48, 168): {'summary': "★★ CmdOEMSupportAssist: TSR (Tech Support Report) export dispatcher. **HOST-ONLY (IsMsgFromSystemInterface gate — LAN can't reach).** Sub-cmds 0x00-0x10 select operation. Upload destination is configurable via iDRAC attributes (DefaultIPAddress / DefaultProtocol / DefaultUserName) — one admin write = persistent exfil to attacker-controlled share. ★★★ if chained with iSM host-side hijack. Full writeup: ~/phd/bmc/dell/idrac-supportassist-export.md.", 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssist'},
    (48, 168, 0): {'summary': 'CmdOEMSupportAssist sub 0x00: NativeOSCollection (host-OS-side TSR collection trigger).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x00'},
    (48, 168, 1): {'summary': 'CmdOEMSupportAssist sub 0x01: collection Started signal (iSM informs BMC).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x01'},
    (48, 168, 2): {'summary': 'CmdOEMSupportAssist sub 0x02: collection Ended signal.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x02'},
    (48, 168, 3): {'summary': '★ CmdOEMSupportAssist sub 0x03: ExposeiSMInstaller (mount the iSM installer image to host).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x03'},
    (48, 168, 4): {'summary': 'CmdOEMSupportAssist sub 0x04: HideiSMInstaller (unmount).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x04'},
    (48, 168, 5): {'summary': 'CmdOEMSupportAssist sub 0x05: GetStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x05'},
    (48, 168, 6): {'summary': '★★ CmdOEMSupportAssist sub 0x06: CollectData (kick off TSR collection — pulls Service Tag, license keys, BIOS settings, IPMI password hashes, sensor inventory, full LCL audit trail, hw inventory, optional host OS event log).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x06'},
    (48, 168, 7): {'summary': 'CmdOEMSupportAssist sub 0x07: GetCollectDataStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x07'},
    (48, 168, 8): {'summary': 'CmdOEMSupportAssist sub 0x08: HideCollectDataResult.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x08'},
    (48, 168, 9): {'summary': '★ CmdOEMSupportAssist sub 0x09: CollectDataCancel (User-priv → DoS primitive against ongoing TSR collection).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x09'},
    (48, 168, 16): {'summary': 'CmdOEMSupportAssist sub 0x10: JobInProgressPendingSignal.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSupportAssistSub0x10'},
    (48, 169): {'summary': 'CmdOEMMASERBonding.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMMASERBonding'},
    (48, 170): {'summary': '★★ CmdOEMMASERLCLAccess: Lifecycle Controller log read+WRITE — log tamper.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMMASERLCLAccess'},
    (48, 171): {'summary': 'CmdOEMGetMASERInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMGetMASERInfo'},
    (48, 172): {'summary': '★★★ CmdOEMRecreateMASER: WIPE eMMC partition table. DESTRUCTIVE.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMRecreateMASER'},
    (48, 173): {'summary': 'CmdOEMGetMASERType.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMGetMASERType'},
    (48, 174): {'summary': 'CmdOEMGetMASERAccessState.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMGetMASERAccessState'},
    (48, 175): {'summary': "★★ CmdOEMSetMASERAccessState: silent forensic disable when set to 'denied'.", 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMSetMASERAccessState'},
    (48, 181): {'summary': 'DellCmdGetFrontPanelInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdGetFrontPanelInfo'},
    (48, 184): {'summary': 'Queue Spd Dimm Info Cmd.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'QueueSpdDimmInfoCmdRead'},
    (48, 185): {'summary': '★★ Queue Spd Dimm Info Cmd (write variant).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'QueueSpdDimmInfoCmdWrite'},
    (48, 188): {'summary': 'Dell CPLDAccess Status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CPLDAccessStatus'},
    (48, 189): {'summary': 'DellCmdIMCFeatureSupport: feature-bitmap of IMC.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdIMCFeatureSupport'},
    (48, 190): {'summary': '★★★ Dell Rollback FW: roll back to backup fw bank — forensic-evasion + downgrade attack.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'RollbackFW'},
    (48, 191): {'summary': 'Dell Get FWVersion.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellGetIDRAC9FWVersion'},
    (48, 192): {'summary': '★★★ Dell PROCHOTThrottle: force PROCHOT# on host CPU. **CRITICAL — instant CPU throttle (silent DoS).**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'PROCHOTThrottle'},
    (48, 193): {'summary': 'Dell GetActiveLOM.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'GetActiveLOM'},
    (48, 194): {'summary': '★★ DellCmdRIPSControl: PSU redundancy/protection control via I2C.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdRIPSControl'},
    (48, 195): {'summary': 'DellCmdCMCFeatureSupport: feature-bitmap of CMC (modular chassis).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdCMCFeatureSupport'},
    (48, 197): {'summary': 'DellDCSGetChassisEncPwrCpng.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassisEncPwrCpng'},
    (48, 198): {'summary': 'DellDCSGetChassisLEDStatus.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetChassisLEDStatus'},
    (48, 199): {'summary': '★ DellDCSSetPSUConfig: chassis PSU config.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetPSUConfig'},
    (48, 200): {'summary': 'SubCmdHandler dispatch root for cmd 0xC8 — Dell Compute Sled (DCS, modular blade chassis). 21 sub-cmds. Full table: ~/phd/bmc/idrac9-firmware/idrac9-subcmdhandler-dispatch.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 200, 2): {'summary': 'DellDCSSubCmdThermalProperties: DCS sled thermal info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdThermalProperties'},
    (48, 200, 3): {'summary': 'DellDCSSubCmdRFSystemInfo: Redfish system info read.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFSystemInfo'},
    (48, 200, 4): {'summary': 'DellDCSSubCmdRFProcInfo: Redfish proc info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFProcInfo'},
    (48, 200, 5): {'summary': 'DellDCSSubCmdRFNICInfo: Redfish NIC info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFNICInfo'},
    (48, 200, 6): {'summary': 'DellDCSSubCmdRFMemInfo: Redfish DIMM info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFMemInfo'},
    (48, 200, 9): {'summary': 'DellDCSSubCmdRFSimpleStorageInfo: Redfish simple-storage info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFSimpleStorageInfo'},
    (48, 200, 16): {'summary': 'DellDCSSubCmdRFStorageDeviceGroupInfo: Redfish storage-device-group info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdRFStorageDeviceGroupInfo'},
    (48, 200, 17): {'summary': 'DellDCSSubCmdMgmtNetworkStatus: chassis mgmt network state.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdMgmtNetworkStatus'},
    (48, 200, 18): {'summary': '★★ DellDCSSubCmdMgmtNetworkCredentials: chassis mgmt network credentials. **AD/SNMP/LDAP-style cred surface — read or set via OEM IPMI.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdMgmtNetworkCredentials'},
    (48, 200, 19): {'summary': 'DellDCSSubCmdSecondPSUInfo: PSU#2 status.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdSecondPSUInfo'},
    (48, 200, 20): {'summary': 'DellDCSSubCmdSetPSUDataForGreyjoy: PSU data write (Greyjoy chassis variant).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSubCmdSetPSUDataForGreyjoy'},
    (48, 200, 22): {'summary': 'DellDCSSetAdditinalPSUInfo: additional PSU info write (sic — typo in symbol).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetAdditinalPSUInfo'},
    (48, 200, 23): {'summary': 'DellDCSSetCmCfgEvent: chassis-mgr config event.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetCmCfgEvent'},
    (48, 200, 24): {'summary': '★★ DellDCSSetSledPowerBudget: per-sled power-budget cap. **Silent DoS — drop sled into low-power cap.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetSledPowerBudget'},
    (48, 200, 25): {'summary': 'DellDCSSetThrottleDebugCodes: throttle-debug codes write.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetThrottleDebugCodes'},
    (48, 200, 26): {'summary': 'DellDCSSetPSUThermal: PSU thermal data write.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetPSUThermal'},
    (48, 200, 27): {'summary': '★★ DellDCSSetSledPowerAlloc: per-sled power allocation. **Silent DoS via power-cap manipulation.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetSledPowerAlloc'},
    (48, 200, 29): {'summary': 'DellDCSSetFanFailure: fault-inject a fan-failure event.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetFanFailure'},
    (48, 200, 30): {'summary': 'DellDCSGetHDDCount: HDD count.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetHDDCount'},
    (48, 200, 31): {'summary': '★ DellDCSSetFansMaxPWM: cap fans to max PWM. **Thermal-attack vector when combined with shutdown-threshold raise (NetFn 0x04 0x26) — defeat thermal protection.**', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetFansMaxPWM'},
    (48, 200, 32): {'summary': 'DellDCSGetSledICL: sled inter-chassis link info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSGetSledICL'},
    (48, 201): {'summary': '★★ DellCmdBladeVirtualMAC: assign virtual MAC to a blade (network identity primitive).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdBladeVirtualMAC'},
    (48, 202): {'summary': '★★★ DelleKmsCmdHlder: Dell eKMS dispatcher. Routes IPMI to KMIP client (libskmip.so) for SED key mgmt. **HIGH attack value if chassis runs SEDs+eKMS.** Full writeup: ~/phd/bmc/dell/dell-cmd-deep-dives.md.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DelleKmsCmdHlder'},
    (48, 203): {'summary': 'DellCmdBladeChassisInfo.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellCmdBladeChassisInfo'},
    (48, 206): {'summary': 'SubCmdHandler dispatch root for cmd 0xCE — DCS Hot-Swap-Controller (HSC). 1 sub-cmd: 0x00 = SetHSCFailure.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 206, 0): {'summary': '★★ DellDCSSetHSCFailure: fault-inject hot-swap-controller failure event. Forensic / fault-evasion primitive.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'DellDCSSetHSCFailure'},
    (48, 207): {'summary': 'SubCmdHandler dispatch root for cmd 0xCF — BMC Pass-Through Attributes. 1 sub-cmd: 0x01 = OSBmcPtAttributes.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 207, 1): {'summary': '★ OSBmcPtAttributes: BMC↔host pass-through attribute config. Host-pivot surface.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'OSBmcPtAttributes'},
    (48, 208): {'summary': '★ CmdOEMMiscCmd: Dell misc dispatcher (sub-byte selects).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'CmdOEMMiscCmd'},
    (48, 209): {'summary': 'SubCmdHandler dispatch root for cmd 0xD1 — Licensing. 8 sub-cmds (license bitmap, device list, statuses).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 209, 1): {'summary': '★ LicensingResetFlag: clear license-cached flag.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensingResetFlag'},
    (48, 209, 2): {'summary': '★ LicensingEntireBitmap: full license bitmap (all features + active/inactive).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensingEntireBitmap'},
    (48, 209, 5): {'summary': "LicensingSingleStatus: query a single licensable feature's status.", 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensingSingleStatus'},
    (48, 209, 6): {'summary': 'LicensableDeviceList: list licensable devices.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensableDeviceList'},
    (48, 209, 7): {'summary': 'LicensableDeviceCurrentClass: current class for a device.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensableDeviceCurrentClass'},
    (48, 209, 8): {'summary': 'LicensableDeviceInformation: device info.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensableDeviceInformation'},
    (48, 209, 9): {'summary': 'LicensableDeviceLicenseList: licenses on a device.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensableDeviceLicenseList'},
    (48, 209, 255): {'summary': 'LicensableDeviceLicenseInfo: per-license info (sub=0xff).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensableDeviceLicenseInfo'},
    (48, 211): {'summary': 'SubCmdHandler dispatch root for cmd 0xD3 — Licensing PCBA test. 1 sub-cmd: 0x02.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 211, 2): {'summary': 'LicensingPCBAtest: PCBA-test license check (factory diag).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'LicensingPCBAtest'},
    (48, 213): {'summary': '★ SubCmdHandler dispatch root for cmd 0xD5 — NO sub-cmd table entries; returns CC error from SubCmdHandler. Reserved cmd byte without active sub-cmds in 9.9.9 fw.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (48, 214): {'summary': '★ SubCmdHandler dispatch root for cmd 0xD6 — NO sub-cmd table entries; returns CC error from SubCmdHandler.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'SubCmdHandler'},
    (50, 1): {'summary': 'iDRAC9 OEM cmd (NetFn 0x32 family — diagnostic/manufacturing).', 'source': 'iDRAC9 RE doc + Dell', 'name': 'iDRAC9OEMCmd_32_01'},
    (50, 2): {'summary': 'iDRAC9 OEM cmd.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'iDRAC9OEMCmd_32_02'},
    (50, 3): {'summary': 'iDRAC9 OEM cmd.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'iDRAC9OEMCmd_32_03'},
    (50, 4): {'summary': 'iDRAC9 OEM cmd.', 'source': 'iDRAC9 RE doc + Dell', 'name': 'iDRAC9OEMCmd_32_04'},
}
