"""
zipmi.scapy_ipmi.oem.idrac9_generated — auto-generated handler catalog.

DO NOT EDIT BY HAND. Regenerate with:
    python -m zipmi.parsers.idrac9_md > zipmi/scapy_ipmi/oem/idrac9_generated.py

Source: iDRAC9 firmware reverse-engineering notes
Entries: 313
"""

from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class IDrac9Handler:
    section: str
    library: str
    cmd_name: str
    handler: str
    notes: str

IDRAC9_HANDLERS: list[IDrac9Handler] = [
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Chassis Control', handler='CmdChassisControl', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Get Chassis Capabilities', handler='CmdGetChassisCapabilities', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Get Chassis Status', handler='CmdGetChassisStatus', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Get System Boot Options', handler='CmdGetSystemBootOptions', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Get System Restart Cause', handler='CmdGetSystemRestartCause', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Set Chassis Capabilities', handler='CmdSetChassisCapabilities', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Set Power Cycle Interval', handler='CmdSetPowerCycleInterval', notes=''),
    IDrac9Handler(section='Chassis', library='libchassiscmds.so', cmd_name='Set System Boot Options', handler='CmdSetSystemBootOptions', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Cold Reset', handler='CmdColdReset', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Get ACPI Power State', handler='CmdGetACPIPowerState', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Get Device GUID', handler='CmdGetDeviceGUID', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Get Device ID', handler='CmdGetDeviceID', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Get Self Test Results', handler='CmdGetSelfTestResults', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Manufacturing Test On', handler='CmdManufacturingTestOn', notes=''),
    IDrac9Handler(section='App / Global', library='libglobalcmds.so', cmd_name='Set ACPI Power State', handler='CmdSetACPIPowerState', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Clear Msg Flags', handler='CmdClearMsgFlags', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Enable Msg Channel Recv', handler='CmdEnableMsgChannelRecv', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Get BMC Global Enable', handler='CmdGetBMCGlobalEnable', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Get Message', handler='CmdGetMsg', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Get Msg Flags', handler='CmdGetMsgFlags', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Read Event Msg Buffer', handler='CmdReadEventMsgBuf', notes=''),
    IDrac9Handler(section='Messaging', library='libmessage.so', cmd_name='Set BMC Global Enable', handler='CmdSetBMCGlobalEnable', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Activate Payload', handler='CmdActivatePayload', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Close Session', handler='CmdCloseSession', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Deactivate Payload', handler='CmdDeactivatePayload', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Auth Code', handler='CmdGetAuthCode', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Access', handler='CmdGetChannelAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Auth Capability', handler='CmdGetChannelAuthCapability', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Cipher Suites', handler='CmdGetChannelCipherSuites', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Info', handler='CmdGetChannelInfo', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel OEM Payload Info', handler='CmdGetChannelOEMPayloadInfo', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Payload Support', handler='CmdGetChannelPayloadSupport', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Channel Payload Version', handler='CmdGetChannelPayloadVersion', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Payload Activation Status', handler='CmdGetPayloadActivationStatus', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Payload Instance Info', handler='CmdGetPayloadInstanceInfo', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get Session Info', handler='CmdGetSessionInfo', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get System GUID', handler='CmdGetSystemGUID', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get User Access', handler='CmdGetUserAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get User Name', handler='CmdGetUserName', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Get User Payload Access', handler='CmdGetUserPayloadAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set Channel Access', handler='CmdSetChannelAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set Channel Security Keys', handler='CmdSetChannelSecurityKeys', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set User Access', handler='CmdSetUserAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set User Name', handler='CmdSetUserName', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set User Password', handler='CmdSetUserPassword', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Set User Payload Access', handler='CmdSetUserPayloadAccess', notes=''),
    IDrac9Handler(section='Session / Payload', library='libpayloadcmds.so', cmd_name='Suspend/Resume Payload Encryption', handler='CmdSuspendResumePayloadEncryption', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Clear SDR', handler='CmdClrSDR', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Get SDR', handler='CmdGetSDR', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Get SDR Repo Info', handler='CmdGetSDRRepoInfo', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Get SDR Repo Time', handler='CmdGetSDRRepoTime', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Partial Add SDR', handler='CmdPartAddSDR', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Reserve SDR Repo', handler='CmdResvSDRRepo', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Run Init Agent', handler='CmdRunInitAgent', notes=''),
    IDrac9Handler(section='SDR Repository', library='libsdr.so', cmd_name='Set SDR Repo Time', handler='CmdSetSDRRepoTime', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Add SEL Entry', handler='CmdAddSELEntry', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Clear SEL', handler='CmdClearSEL', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Get SEL Entry', handler='CmdGetSELEntry', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Get SEL Info', handler='CmdGetSELInfo', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Get SEL Time', handler='CmdGetSELTime', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Reserve SEL', handler='CmdReserveSEL', notes=''),
    IDrac9Handler(section='SEL', library='libselcmds.so', cmd_name='Set SEL Time', handler='CmdSetSELTime', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Event Enable', handler='CmdGetSensorEventEnable', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Event Status', handler='CmdGetSensorEventStatus', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Hysteresis', handler='CmdGetSensorHysteresis', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Reading', handler='CmdGetSensorReading', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Reading Factors', handler='CmdGetSensorReadingFactors', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Thresholds', handler='CmdGetSensorThresholds', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Get Sensor Type', handler='CmdGetSensorType', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Rearm Sensor Events', handler='CmdRearmSensorEvents', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Set Sensor Event Enable', handler='CmdSetSensorEventEnable', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Set Sensor Hysteresis', handler='CmdSetSensorHysteresis', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Set Sensor Reading', handler='CmdSetSensorReading', notes=''),
    IDrac9Handler(section='Sensor/Event', library='libsensorcmds.so', cmd_name='Set Sensor Thresholds', handler='CmdSetSensorThresholds', notes=''),
    IDrac9Handler(section='Sensor Event', library='libsensorevent.so', cmd_name='Get Event Receiver', handler='CmdGetEventReceiver', notes=''),
    IDrac9Handler(section='Sensor Event', library='libsensorevent.so', cmd_name='Platform Event', handler='CmdPlatformEvent', notes=''),
    IDrac9Handler(section='Sensor Event', library='libsensorevent.so', cmd_name='Set Event Receiver', handler='CmdSetEventReceiver', notes=''),
    IDrac9Handler(section='FRU', library='libifru.so', cmd_name='Get FRU Inv Area Info', handler='CmdGetFRUInvAreaInfo', notes=''),
    IDrac9Handler(section='FRU', library='libifru.so', cmd_name='Read FRU Data', handler='CmdReadFRUData', notes=''),
    IDrac9Handler(section='FRU', library='libifru.so', cmd_name='Write FRU Data', handler='CmdWriteFRUData', notes=''),
    IDrac9Handler(section='LAN', library='liblancmds.so', cmd_name='Get IP Statistics', handler='CmdGetIPStatistics', notes=''),
    IDrac9Handler(section='LAN', library='liblancmds.so', cmd_name='Get LAN Config Param', handler='CmdGetLANConfigParam', notes=''),
    IDrac9Handler(section='LAN', library='liblancmds.so', cmd_name='Set LAN Config Param', handler='CmdSetLANConfigParam', notes=''),
    IDrac9Handler(section='LAN', library='liblancmds.so', cmd_name='Suspend BMC ARPs', handler='CmdSuspendBMCARPs', notes=''),
    IDrac9Handler(section='SOL', library='libchnl.so', cmd_name='Get SOL Configuration', handler='CmdGetSOLConfiguration', notes=''),
    IDrac9Handler(section='SOL', library='libchnl.so', cmd_name='Set SOL Configuration', handler='CmdSetSOLConfiguration', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Callback', handler='CmdCallback', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get PPP/UDP Proxy Tx Data', handler='CmdGetPPPUDPProxyTxData', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get PPP/UDP Receive Data', handler='CmdGetPPPUDPReceiveData', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get Serial/Modem Config Param', handler='CmdGetSerModemConfigParam', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get System Boot Options', handler='CmdGetSystemBootOptions', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get TAP Response Codes', handler='CmdGetTapResponseCodes', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Get User Callback Options', handler='CmdGetUserCallbackOptions', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Send PPP/UDP Proxy Packet', handler='CmdSendPPPUDPProxyPacket', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set PPP/UDP Proxy Tx Data', handler='CmdSetPPPUDPProxyTxData', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set Serial/Modem Config Param', handler='CmdSetSerModemConfigParam', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set Serial/Modem Mux', handler='CmdSetSerModemMux', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set Serial Routing Mux', handler='CmdSetSerRoutingMux', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set System Boot Options', handler='CmdSetSystemBootOptions', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Set User Callback Options', handler='CmdSetUserCallbackOptions', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Terminal SYS', handler='CmdTerminalSYS', notes=''),
    IDrac9Handler(section='Serial/Modem', library='libserialcmds.so', cmd_name='Terminal SYSDRAC', handler='CmdTerminalSYSDRAC', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Alert Immediate', handler='CmdPEFCAlertImmediate', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Arm Postpone Timer', handler='CmdPEFCArmPostponeTimer', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Get Capabilities', handler='CmdPEFCGetCapabilities', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Get Config Params', handler='CmdPEFCGetConfigurationParameters', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Get Last Processed Event ID', handler='CmdPEFCGetLastProcessedEventID', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Set Config Params', handler='CmdPEFCSetConfigurationParameters', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PEFC Set Last Processed Event ID', handler='CmdPEFCSetLastProcessedEventID', notes=''),
    IDrac9Handler(section='PEF', library='libpefcmds.so', cmd_name='PETC Acknowledge', handler='CmdPETCAcknowledge', notes=''),
    IDrac9Handler(section='Watchdog', library='libiwdg.so', cmd_name='Get Watchdog Timer', handler='CmdGetWatchdogTimer', notes=''),
    IDrac9Handler(section='Watchdog', library='libiwdg.so', cmd_name='Reset Watchdog Timer', handler='CmdResetWatchdogTimer', notes=''),
    IDrac9Handler(section='Watchdog', library='libiwdg.so', cmd_name='Set Watchdog Timer', handler='CmdSetWatchdogTimer', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Cancel Firmware Update', handler='CmdCancelFirmwareUpdate', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Firmware Update', handler='CmdFirmwareUpdate', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Firmware Update Phase 1', handler='CmdFirmwareUpdatePhase1', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Firmware Update Phase 2', handler='CmdFirmwareUpdatePhase2', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get BMC SA', handler='CmdGetBMCSA', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get Dyn Alloc Memory Size', handler='CmdGetDynaAllocMemorySize', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get FW ID', handler='CmdGetFWID', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get FW Version', handler='CmdGetFWVersion', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get Firmware Update Status', handler='CmdGetFirmwareUpdateStatus', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Get Firmware Version', handler='CmdGetFirmwareVersion', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Memory Check', handler='CmdMemoryChk', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='OSA OEM Cmd Handler', handler='CmdOSAOEMCmdHandler', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Reset To Default', handler='CmdResetToDefault', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Reset To Default OSA', handler='CmdResetToDefaultOSA', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Rollback Firmware Version', handler='CmdRollbackFirmwareVersion', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Sensor Test', handler='CmdSensorTest', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Set BMC SA', handler='CmdSetBMCSA', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Set FW Image Status', handler='CmdSetFWImageStatus', notes=''),
    IDrac9Handler(section='Firmware Update', library='libosa.so', cmd_name='Set Sys GUID', handler='CmdSetSysGUID', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Command Enables', handler='CmdGetCommandEnables', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Command SubFn Enables', handler='CmdGetCommandSubFnEnables', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Command SubFn Support', handler='CmdGetCommandSubFnSupport', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Command Support', handler='CmdGetCommandSupport', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Configurable Command SubFn', handler='CmdGetConfigurableCommandSubFn', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get Configurable Commands', handler='CmdGetConfigurableCommands', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get NetFn Support', handler='CmdGetNetFnSupport', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Get OEM NetFn IANA Support', handler='CmdGetOEMNetFnIANASupport', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Set Command Enables', handler='CmdSetCommandEnables', notes=''),
    IDrac9Handler(section='Firewall', library='libfirewall.so', cmd_name='Set Command SubFn Enables', handler='CmdSetCommandSubFnEnables', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get DCMI Capability Info', handler='CmdDcmiGetDcmiCapabilityInfo', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get DCMI Sensor Info', handler='CmdDcmiGetDcmiSensorInfo', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Asset Tag', handler='CmdDcmiGetAssetTag', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Set Asset Tag', handler='CmdDcmiSetAssetTag', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Management Controller ID', handler='CmdDcmiGetManagementControllerIdStr', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Set Management Controller ID', handler='CmdDcmiSetManagementControllerIdStr', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get DCMI Config Param', handler='CmdDcmiGetDMCIConfigParam', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Set DCMI Config Param', handler='CmdDcmiSetDMCIConfigParam', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Power Reading', handler='CmdDcmiGetPowerReading', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Power Limit', handler='CmdDcmiGetPowerLimit', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Set Power Limit', handler='CmdDcmiSetPowerLimit', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Activate/Deactivate Power Limit', handler='CmdDcmiActDeactPowerLimit', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Temperature Readings', handler='CmdDcmiGetTemperatureReadings', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Get Thermal Limit', handler='CmdDcmiGetThermalLimit', notes=''),
    IDrac9Handler(section='DCMI', library='libdcmi.so', cmd_name='Set Thermal Limit', handler='CmdDcmiSetThermalLimit', notes=''),
    IDrac9Handler(section='OEM Chassis / Identity', library='', cmd_name='OEM Chassis Identify', handler='CmdOEMChassisIdentify', notes='LED control'),
    IDrac9Handler(section='OEM Chassis / Identity', library='', cmd_name='Get Chassis Capabilities', handler='CmdOEMGetChassisCapabilities', notes=''),
    IDrac9Handler(section='OEM Chassis / Identity', library='', cmd_name='Set Chassis Capabilities', handler='CmdOEMSetChassisCapabilities', notes=''),
    IDrac9Handler(section='OEM Chassis / Identity', library='', cmd_name='Get Self Test Results', handler='CmdOEMGetSelfTestResults', notes=''),
    IDrac9Handler(section='OEM Chassis / Identity', library='', cmd_name='Get Command Support', handler='CmdOEMGetCommandSupport', notes=''),
    IDrac9Handler(section='OEM I2C/Hardware Direct Access', library='', cmd_name='I2C Write/Read', handler='CmdI2CWriteRead_OEM', notes='DIRECT I2C BUS ACCESS — can reach VRMs, SPDs, CPLD, PMBus devices'),
    IDrac9Handler(section='OEM I2C/Hardware Direct Access', library='', cmd_name='Manufacturing Test On', handler='CmdOEMManufacturingTestOn', notes='Enables factory test mode'),
    IDrac9Handler(section='OEM I2C/Hardware Direct Access', library='', cmd_name='Dell Factory', handler='CmdOEMDellFactory', notes='Factory provisioning — creates hw inventory, resets'),
    IDrac9Handler(section='OEM User / Auth', library='', cmd_name='Set User Password', handler='CmdOEMSetUserPassword', notes='OEM password change path'),
    IDrac9Handler(section='OEM User / Auth', library='', cmd_name='Remote Enablement', handler='CmdOEMRemoteEnablement', notes='Auto-discovery / zero-touch provisioning'),
    IDrac9Handler(section='OEM User / Auth', library='', cmd_name='Enable Msg Channel Recv', handler='CmdOEMEnableMsgChannelRecv', notes=''),
    IDrac9Handler(section='OEM User / Auth', library='', cmd_name='Get Channel Info', handler='CmdOEMGetChannelInfo', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Get MASER Access State', handler='CmdOEMGetMASERAccessState', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Set MASER Access State', handler='CmdOEMSetMASERAccessState', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Get MASER Info', handler='CmdOEMGetMASERInfo', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Get MASER Type', handler='CmdOEMGetMASERType', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='MASER LCL Access', handler='CmdOEMMASERLCLAccess', notes='Lifecycle controller access'),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='MASER Partition Access', handler='CmdOEMMASERPartitionAccess', notes='eMMC partition control'),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='MASER PM', handler='CmdOEMMASER_PM', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='POST MASER Access', handler='CmdOEMPOSTMASERAccess', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Recreate MASER', handler='CmdOEMRecreateMASER', notes='Wipe/recreate storage'),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Lock MASER', handler='CmdOEMLockMASER', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Unlock MASER', handler='CmdOEMUnLockMASER', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='MASER Lock WD Reset', handler='CmdOEMMASERLockWDreset', notes=''),
    IDrac9Handler(section='OEM MASER (Non-Volatile Storage)', library='libmaser.so', cmd_name='Backup/Restore', handler='CmdOEMBackupRestore', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Get USC Version', handler='CmdOEMLCLGetUSCVer', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Get Status', handler='CmdOEMLCLMASERGetLCLStatus', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL HW Inventory', handler='CmdOEMLCLMASERHWInventory', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Factory HW Inventory Get', handler='CmdOEMLCLMASERFactoryHWInventoryGet', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL History', handler='CmdOEMLCLMASERHistory', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Log Entry', handler='CmdOEMLCLMASERLogEntry', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Query Current Records', handler='CmdOEMLCLMASERQueryCurrentRecords', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Query Event Record', handler='CmdOEMLCLMASERQueryEventRecord', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Query Record History', handler='CmdOEMLCLMASERQueryRecordHistory', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Query Dependency', handler='CmdOEMLCLMASERQueryDependency', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Update Entire Inventory', handler='CmdOEMLCLMASERUpdateEntireInventory', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Update Inventory Records', handler='CmdOEMLCLMASERUpdateInventoryRecords', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Update XML Records', handler='CmdOEMLCLMASERUpdateXMLRecords', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Copy MUT Data', handler='CmdOEMLCLCopyMUTData', notes=''),
    IDrac9Handler(section='OEM MASER', library='', cmd_name='LCL Wipe', handler='CmdOEMLCLWipe', notes='Wipes Lifecycle Controller'),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Card Control', handler='CmdOEMVflashCardControl', notes='Enable/Disable/Initialize SD'),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Card Info', handler='CmdOEMVflashGetCardInfo', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Create Empty Partition', handler='CmdOEMVflashCreateEmptyPartition', notes='Supports FAT16/FAT32/EXT2/EXT3/RAW'),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Delete Partition', handler='CmdOEMVflashDeletePartition', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Format Partition', handler='CmdOEMVflashFormatPartition', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Attach Partitions', handler='CmdOEMVflashAttachPartitions', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Detach Partitions', handler='CmdOEMVflashDetachPartitions', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Change Access Type', handler='CmdOEMVflashChangePartitionAccessType', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Partition Info', handler='CmdOEMLVflashGetPartitionInfo', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Partition Index Info', handler='CmdOEMLVflashGetPartitionIndexInfo', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Boot Partition', handler='CmdOEMVflashGetBootPartition', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Set Boot Partition', handler='CmdOEMVflashSetBootPartition', notes='Controls which partition boots'),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Job Status', handler='CmdOEMVflashGetJobStatus', notes=''),
    IDrac9Handler(section='OEM vFlash (Virtual SD Card)', library='libmaser.so', cmd_name='vFlash Get Partition Status', handler='CmdOEMVflashGetPartitionStatus', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Begin SECUPD', handler='CmdOEMBeginSECUPD', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='End SECUPD', handler='CmdOEMEndSECUPD', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Process SECUPD', handler='CmdOEMProcessSECUPD', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Start SECUPD PM', handler='CmdOEMStartSECUPD_PM', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Populate Backup Cmd', handler='CmdOEMBnRPopulateBackupCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Send Backup Cmd', handler='CmdOEMBnRSendBackupCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Populate Restore Cmd', handler='CmdOEMBnRPopulateRestoreCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Send Restore Cmd', handler='CmdOEMBnRSendRestoreCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Query Job ID', handler='CmdOEMBnRQueryJobID', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Query Job Status', handler='CmdOEMBnRQueryJobStatus', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Set Job Status', handler='CmdOEMBnRSetJobStatusCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Cancel', handler='CmdOEMBnRCancelCmd', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Get Auto Feature Status', handler='CmdOEMBnRGetAutoFeatureStatus', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='BnR Get Auto Restore VFL Cap', handler='CmdOEMBnRGetAutoRestoreVflCap', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Secure Update Partition', handler='CmdOEMSecureUpdatePartition', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Compliant Update Validate', handler='CmdOEMCmplntUpdValidate', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Compliant Update Status', handler='CmdOEMCmplntUpdValidateStatus', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Compliant Update', handler='CmdOEMCmplntUpdUpdate', notes=''),
    IDrac9Handler(section='OEM Backup/Restore', library='libmaser.so', cmd_name='Compliant Update Query Status', handler='CmdOEMCmplntUpdQueryStatus', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get Auto Discovery', handler='CmdOEMGetAutoDiscovery', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Set Auto Discovery', handler='CmdOEMSetAutoDiscovery', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get Provisioning Server Info', handler='CmdOEMGetProvisioningServerInfo', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Set Provisioning Server Info', handler='CmdOEMSetProvisioningServerInfo', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get Discovery Restart Options', handler='CmdOEMGetDiscoveryRestartOptions', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Set Discovery Restart Options', handler='CmdOEMSetDiscoveryRestartOptions', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get RE Capabilities Bitmap', handler='CmdOEMGetRECapabilitiesBitmap', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Set RE Capabilities Bitmap', handler='CmdOEMSetRECapabilitiesBitmap', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='RE Capability For DUP', handler='CmdOEMReCapabilityForDup', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get PM Status', handler='CmdOEMGetPMStatus', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get PM Default Brand', handler='CmdOEMGetPMDefaultBrand', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get PM Rebrand', handler='CmdOEMGetPMRebrand', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Set PM Install', handler='CmdOEMSetPMInstall', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get PM Update Flag', handler='CmdOEMGetPMUpdateFlag', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Clear PM Update Flag', handler='CmdOEMClrPMUpdateFlag', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get Pkg Cache Update Flag', handler='CmdOEMGetPkgCacheUpdateFlag', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Get Certificate Status', handler='CmdOEMGetCertificateStatus', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Remove Certificate', handler='CmdOEMRemoveCertificate', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Sign Certificate', handler='CmdOEMSignCertificate', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Secure Default Password', handler='CmdOEMSecureDefaultPassword', notes=''),
    IDrac9Handler(section='OEM Licensing / Provisioning', library='', cmd_name='Bootstrap Credentials Control', handler='CmdCmdBootstrapCredentialsControl', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Get CCR Feature State', handler='CmdOEMGetCCRFeatureState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Set CCR Feature State', handler='CmdOEMSetCCRFeatureState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Get CCR Config State', handler='CmdOEMGetCCRConfigurationState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Set CCR Config State', handler='CmdOEMSetCCRConfigurationState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Get CCR Auto Sync State', handler='CmdOEMGetCCRAutoSyncState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Set CCR Auto Sync State', handler='CmdOEMSetCCRAutoSyncState', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Get CCR Update FW Mode', handler='CmdOEMGetCCRUpdateFWMode', notes=''),
    IDrac9Handler(section='OEM CCR (Config Change Recording)', library='', cmd_name='Set CCR Update FW Mode', handler='CmdOEMSetCCRUpdateFWMode', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SupportAssist', handler='CmdOEMSupportAssist', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Collect Data', handler='CmdOEMSACollectData', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Collect Data Cancel', handler='CmdOEMSACollectDataCancel', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Get Collect Data Status', handler='CmdOEMSAGetCollectDataStatus', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Get Status', handler='CmdOEMSAGetStatus', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Expose iSM Installer', handler='CmdOEMSAExposeiSMInstaller', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Hide iSM Installer', handler='CmdOEMSAHideiSMInstaller', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Hide Collect Data Result', handler='CmdOEMSAHideCollectDataResult', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Native OS Collection', handler='CmdOEMSANativeOSCollection', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Native OS Collection Started', handler='CmdOEMSANativeOSCollectionStarted', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Native OS Collection Ended', handler='CmdOEMSANativeOSCollectionEnded', notes=''),
    IDrac9Handler(section='OEM SupportAssist', library='', cmd_name='SA Job In Progress Signal', handler='CmdOEMSAJobInProgressPendingSignal', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='Tool Set', handler='CmdOEMToolSet', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Begin Marker', handler='CmdOEMTSBeginMarker', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS End Marker', handler='CmdOEMTSEndMarker', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Update Marker', handler='CmdOEMTSUpdateMarker', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Collect Data', handler='CmdOEMTSCollectData', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Get Data Info', handler='CmdOEMTSGetDataInfo', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Get Status', handler='CmdOEMTSGetStatus', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Expose Execs', handler='CmdOEMTSExposeExecs', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS Hide Execs', handler='CmdOEMTSHideExecs', notes=''),
    IDrac9Handler(section='OEM Tool Set (TS)', library='', cmd_name='TS System Erase', handler='CmdOEMTSSystemErase', notes='System erase via IPMI'),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='Get UEFI Flag', handler='CmdOEMGetUEFIFlag', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='Set UEFI Flag', handler='CmdOEMSetUEFIFlag', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='Get BIOS Password Info', handler='CmdOEMGetBIOSPasswordInfo', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST Set BIOS Password', handler='CmdOEMPOSTSetBIOSPassword', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST Set BIOS SHA Password', handler='CmdOEMPOSTSetBIOSSHAPassword', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST Get Boot Vol Label', handler='CmdOEMPOSTGetBootVolLabel', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST Log LCL Event', handler='CmdOEMPOSTLogLCLEvent', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST MASER Attach Partition', handler='CmdOEMPOSTMASERAttachPartition', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST MASER Detach Partition', handler='CmdOEMPOSTMASERDetachPartition', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST MASER Get Prov Options', handler='CmdOEMPOSTMASERGetProvOptions', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='POST MASER Set System Req', handler='CmdOEMPOSTMASERSetSystemReq', notes=''),
    IDrac9Handler(section='OEM BIOS/UEFI', library='', cmd_name='UEFI Log Service', handler='CmdOEMUEFILOGService', notes=''),
    IDrac9Handler(section='OEM Misc', library='libmisccmd.so', cmd_name='OEM Misc Cmd', handler='CmdOEMMiscCmd', notes='Dispatch for misc OEM sub-commands'),
    IDrac9Handler(section='OEM Misc', library='libmisccmd.so', cmd_name='OEM Power Avg Range', handler='CmdOEMPwrAvgRange', notes='Power consumption data'),
    IDrac9Handler(section='OEM Misc', library='libmisccmd.so', cmd_name='OEM Power Headroom', handler='CmdOEMPwrHeadroom', notes='Instantaneous + peak headroom (watts)'),
    IDrac9Handler(section='OEM Misc', library='libmisccmd.so', cmd_name='Get NIC Selection Failover', handler='CmdGetNICSelectionFailover', notes=''),
    IDrac9Handler(section='OEM Misc', library='libmisccmd.so', cmd_name='Set NIC Selection Failover', handler='CmdSetNICSelectionFailover', notes=''),
    IDrac9Handler(section='OEM SEL/FRU (via `libmodular.so`)', library='libmodular.so', cmd_name='OEM Get SEL Entry', handler='CmdOEMGetSELEntry', notes=''),
    IDrac9Handler(section='OEM SEL/FRU (via `libmodular.so`)', library='libmodular.so', cmd_name='OEM Read FRU Data', handler='CmdOEMReadFRUData', notes=''),
    IDrac9Handler(section='OEM SEL/FRU (via `libmodular.so`)', library='libmodular.so', cmd_name='OEM Set SEL Time', handler='CmdOEMSetSELTime', notes=''),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Reserve Extended Configure', handler='CmdResvExtendedConfigure', notes=''),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Get Extended Configure', handler='CmdGetExtendedConfigure', notes=''),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Set Extended Configure', handler='CmdSetExtendedConfigure', notes='Modifies BMC configuration'),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Set Power Restore Policy', handler='CmdSetPowerRestorePolicy', notes=''),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Set Sensor Thresholds Override', handler='CmdSetSensorThresholdsOverride', notes='Can override safety thresholds'),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='POST Event', handler='CmdPOSTEvent', notes=''),
    IDrac9Handler(section='OEM Extended Configure', library='liboemcmds.so', cmd_name='Get Soft Lock Status', handler='CmdGetSoftLockStatus', notes=''),
    IDrac9Handler(section='OEM Network ISO', library='', cmd_name='Disconnect Network ISO', handler='CmdOEMDisconnectNetworkISO', notes=''),
    IDrac9Handler(section='OEM Network ISO', library='', cmd_name='Skip ISO Boot', handler='CmdOEMSkipISOBoot', notes=''),
    IDrac9Handler(section='OEM Utility', library='libmaser.so', cmd_name='OEM Utility', handler='CmdOEMUtility', notes='Sub-command dispatch: factory reset, secure default password, offline DB sync'),
    IDrac9Handler(section='OEM Utility', library='libmaser.so', cmd_name='Single IPMI', handler='CmdOEMSingleIPMI', notes=''),
    IDrac9Handler(section='OEM Utility', library='libmaser.so', cmd_name='Forwarded Cmds', handler='CmdForwardedCmds', notes=''),
]

# Quick-lookup dicts.
HANDLERS_BY_NAME: dict[str, IDrac9Handler] = {h.handler: h for h in IDRAC9_HANDLERS}
HANDLERS_BY_LIBRARY: dict[str, list[IDrac9Handler]] = {}
for _h in IDRAC9_HANDLERS:
    HANDLERS_BY_LIBRARY.setdefault(_h.library or '(none)', []).append(_h)
