"""zipmi.scapy_ipmi.oem.idrac6_known_context — Dell BMC context overlay.

Hand-curated entries from full audit of every Dell iDRAC6 OEM cmd
plus the std-IPMI cmds Dell ships handlers for. Sources:
  - iDRAC6 firmware (fullfw) binary (radare2 RE)
  - Dell iDRAC OEM RE notes research notes
  - IPMI 2.0 spec (for the std cmds)
  - Dell iDRAC OEM command deep-dives (internal RE) (per-cmd writeups)

Risk markers in summaries:
  ★    interesting / non-obvious behaviour
  ★★   sensitive (admin escalation surface)
  ★★★  destructive / critical (data loss, brick risk, host attack)

Reservation flows wired for SDR, SEL, and Dell ResvExtendedConfigure.
"""

KNOWN_CONTEXT: dict[tuple, dict] = {
    (0, 0): {'summary': 'Get Chassis Capabilities. Returns 6 bytes: cap flags + 4 IPMB addresses (FRU/SDR/SEL/MainCh).', 'source': 'Dell RE doc + binary', 'name': 'GetChassisCapabilities'},
    (0, 1): {'summary': "Get Chassis Status. Returns power state, last-power-event cause, misc state. T710 live: '21 10 00 50' = ON.", 'source': 'Dell RE doc + binary', 'name': 'GetChassisStatus'},
    (0, 2): {'summary': "★ Chassis Control. data[0]: 0x00=down/0x01=up/0x02=cycle/0x03=hard-reset/0x04=diag-int/0x05=soft. ★★ '0x03' is the BMC's nuclear-option reset.", 'source': 'Dell RE doc + binary', 'name': 'ChassisControl'},
    (0, 4): {'summary': 'Chassis Identify. data[0]=duration (sec); data[1]=force (1=indefinite). Blinks the front-panel UID LED.', 'source': 'Dell RE doc + binary', 'name': 'ChassisIdentify'},
    (0, 5): {'summary': 'Set Chassis Capabilities. ★ writes the cap flags returned by 0x30 0x00 — admin-only.', 'source': 'Dell RE doc + binary', 'name': 'SetChassisCapabilities'},
    (0, 7): {'summary': 'Get System Restart Cause. Returns: cause byte + channel (chassis cmd / pushbutton / WD / etc.).', 'source': 'Dell RE doc + binary', 'name': 'GetSystemRestartCause'},
    (0, 8): {'summary': '★★ Set System Boot Options. Writes the BIOS boot device + flags. Used by `chassis bootdev pxe/disk/cdrom` etc. **Also: persistent-vs-onetime bit lets attacker pin the boot device.**', 'source': 'Dell RE doc + binary', 'name': 'SetSystemBootOptions'},
    (0, 9): {'summary': 'Get System Boot Options. Reads back the parameter set by 0x08. Live: 0xC7 (needs param byte).', 'source': 'Dell RE doc + binary', 'name': 'GetSystemBootOptions'},
    (0, 11): {'summary': 'Set Power Cycle Interval. data[0]=delay (sec). Affects how 0x02 sub-cmd 0x02 (cycle) behaves.', 'source': 'Dell RE doc + binary', 'name': 'SetPowerCycleInterval'},
    (4, 0): {'summary': 'Set Event Receiver. Configures IPMB addr+LUN where SEL events get sent.', 'source': 'Dell RE doc + binary', 'name': 'SetEventReceiver'},
    (4, 1): {'summary': 'Get Event Receiver. Returns currently-configured target.', 'source': 'Dell RE doc + binary', 'name': 'GetEventReceiver'},
    (4, 2): {'summary': 'Platform Event Message. ★ Used to inject events into SEL — useful for testing alert paths, also for log-spoofing.', 'source': 'Dell RE doc + binary', 'name': 'PlatformEvent'},
    (4, 16): {'summary': 'PEF Get Capabilities. Reports filter/policy table sizes. T710: PEF v1.5, 31 filters, 40 policies.', 'source': 'Dell RE doc + binary', 'name': 'GetPEFCapabilities'},
    (4, 17): {'summary': 'PEF Arm Postpone Timer. Watchdog for PEF — arm 0 to disable, otherwise countdown.', 'source': 'Dell RE doc + binary', 'name': 'ArmPEFPostponeTimer'},
    (4, 18): {'summary': '★★ PEF Set Configuration Parameters. Writes filter/policy/community-string/trap-dest config. Reservation-protected.', 'source': 'Dell RE doc + binary', 'name': 'SetPEFConfigurationParameters'},
    (4, 19): {'summary': 'PEF Get Configuration Parameters. Reads PEF config back. Live: 0xC7 needs param byte.', 'source': 'Dell RE doc + binary', 'name': 'GetPEFConfigurationParameters'},
    (4, 20): {'summary': 'PEF Set Last Processed Event ID. Marks SEL processing checkpoint.', 'source': 'Dell RE doc + binary', 'name': 'SetLastProcessedEventID'},
    (4, 21): {'summary': 'PEF Get Last Processed Event ID. Returns SEL/SW checkpoint.', 'source': 'Dell RE doc + binary', 'name': 'GetLastProcessedEventID'},
    (4, 22): {'summary': '★ PEF Alert Immediate. Triggers a configured alert NOW — useful to test SNMP trap dest config.', 'source': 'Dell RE doc + binary', 'name': 'AlertImmediate'},
    (4, 23): {'summary': 'PETC Acknowledge. Acknowledges a Platform Event Trap (PET).', 'source': 'Dell RE doc + binary', 'name': 'PETAcknowledge'},
    (4, 35): {'summary': '★ Get Sensor Reading Factors. Required for raw-value-to-engineering-unit conversion of certain sensor types.', 'source': 'Dell RE doc + binary', 'name': 'GetSensorReadingFactors'},
    (4, 36): {'summary': '★★ Set Sensor Hysteresis. Writes per-sensor hysteresis values. Combined with 0x26 = thermal-protection bypass.', 'source': 'Dell RE doc + binary', 'name': 'SetSensorHysteresis'},
    (4, 37): {'summary': 'Get Sensor Hysteresis. Live: 0xC7 needs 2-byte sensor#.', 'source': 'Dell RE doc + binary', 'name': 'GetSensorHysteresis'},
    (4, 38): {'summary': '★★★ Set Sensor Thresholds. Writes upper/lower critical/non-critical thresholds. **CRITICAL — raise thermal-shutdown threshold to defeat protective shutdowns during a thermal/load attack.**', 'source': 'Dell RE doc + binary', 'name': 'SetSensorThreshold'},
    (4, 39): {'summary': "Get Sensor Thresholds. Live (sensor 1): '18 00 00 00 d5 da 00' — UC=0xD5, UNR=0xDA.", 'source': 'Dell RE doc + binary', 'name': 'GetSensorThreshold'},
    (4, 40): {'summary': 'Set Sensor Event Enable. Enables/disables event generation per-threshold per-sensor.', 'source': 'Dell RE doc + binary', 'name': 'SetSensorEventEnable'},
    (4, 41): {'summary': 'Get Sensor Event Enable.', 'source': 'Dell RE doc + binary', 'name': 'GetSensorEventEnable'},
    (4, 42): {'summary': 'Re-arm Sensor Events. Forces a sensor to re-evaluate its assertion state.', 'source': 'Dell RE doc + binary', 'name': 'ReArmSensorEvents'},
    (4, 43): {'summary': 'Get Sensor Event Status.', 'source': 'Dell RE doc + binary', 'name': 'GetSensorEventStatus'},
    (4, 45): {'summary': 'Get Sensor Reading. The bread-and-butter sensor query — returns raw reading + state bitmap.', 'source': 'Dell RE doc + binary', 'name': 'GetSensorReading'},
    (4, 48): {'summary': 'Set Sensor Reading. ★ allows pushing a synthetic reading; many BMCs lock this to mfg mode but Dell allows admin.', 'source': 'Dell RE doc + binary', 'name': 'SetSensorReadingAndEventStatus'},
    (6, 1): {'summary': 'Get Device ID. THE first cmd anyone sends. Returns mfg ID (Dell=674), product ID, firmware rev, IPMI ver, etc.', 'source': 'Dell RE doc + binary', 'name': 'GetDeviceID'},
    (6, 2): {'summary': '★★ Cold Reset. Reboots the BMC. NOT a host reset — just the management controller. Sessions drop.', 'source': 'Dell RE doc + binary', 'name': 'ColdReset'},
    (6, 3): {'summary': 'Warm Reset. Soft re-init of the BMC (no full power cycle). Usually unimplemented; T710 likely returns 0xC1.', 'source': 'Dell RE doc + binary', 'name': 'WarmReset'},
    (6, 4): {'summary': 'Get Self Test Results. Returns 2-byte self-test code (0x55 = pass).', 'source': 'Dell RE doc + binary', 'name': 'GetSelfTestResults'},
    (6, 5): {'summary': '★★★ Manufacturing Test On. Unlocks factory test mode — exposes hidden cmds + weakens auth checks. **DO NOT run on production BMCs.**', 'source': 'Dell RE doc + binary', 'name': 'ManufacturingTestOn'},
    (6, 6): {'summary': "Set ACPI Power State. Tracks the host's S-state from the BMC's view.", 'source': 'Dell RE doc + binary', 'name': 'SetACPIPowerState'},
    (6, 7): {'summary': 'Get ACPI Power State.', 'source': 'Dell RE doc + binary', 'name': 'GetACPIPowerState'},
    (6, 8): {'summary': 'Get Device GUID. 16-byte BMC GUID.', 'source': 'Dell RE doc + binary', 'name': 'GetDeviceGUID'},
    (6, 9): {'summary': 'Get NetFn Support. Per-NetFn enable bitmap — query what the BMC accepts.', 'source': 'Dell RE doc + binary', 'name': 'GetNetFnSupport'},
    (6, 10): {'summary': 'Get Command Support. Per-(NetFn,cmd) enable bitmap.', 'source': 'Dell RE doc + binary', 'name': 'GetCommandSupport'},
    (6, 11): {'summary': 'Get Command Sub-function Support.', 'source': 'Dell RE doc + binary', 'name': 'GetCommandSubFunctionSupport'},
    (6, 12): {'summary': 'Get Configurable Commands.', 'source': 'Dell RE doc + binary', 'name': 'GetConfigurableCommands'},
    (6, 13): {'summary': 'Get Configurable Command Sub-functions.', 'source': 'Dell RE doc + binary', 'name': 'GetConfigurableCommandSubFunctions'},
    (6, 34): {'summary': 'Reset Watchdog Timer. ★ Pet-the-watchdog. Must be sent before timeout to avoid BMC-driven host reset.', 'source': 'Dell RE doc + binary', 'name': 'ResetWatchdogTimer'},
    (6, 36): {'summary': '★ Set Watchdog Timer. Configures the watchdog: action (reset/down/cycle/diag), timeout, pre-action timer.', 'source': 'Dell RE doc + binary', 'name': 'SetWatchdogTimer'},
    (6, 37): {'summary': 'Get Watchdog Timer. Reads current config + remaining time.', 'source': 'Dell RE doc + binary', 'name': 'GetWatchdogTimer'},
    (6, 46): {'summary': 'Set BMC Global Enables. Toggles event-msg-buffer, OEM 0/1/2, system-event-log, receive-msg-queue.', 'source': 'Dell RE doc + binary', 'name': 'SetBMCGlobalEnables'},
    (6, 47): {'summary': 'Get BMC Global Enables.', 'source': 'Dell RE doc + binary', 'name': 'GetBMCGlobalEnables'},
    (6, 48): {'summary': 'Clear Message Flags. Clears pending OEM/RxMsgQ/EvtMsgBuf flags.', 'source': 'Dell RE doc + binary', 'name': 'ClearMessageFlags'},
    (6, 49): {'summary': 'Get Message Flags. Reads which message types are pending.', 'source': 'Dell RE doc + binary', 'name': 'GetMessageFlags'},
    (6, 50): {'summary': 'Enable Message Channel Receive. Per-channel enable for unsolicited messages.', 'source': 'Dell RE doc + binary', 'name': 'EnableMessageChannelReceive'},
    (6, 51): {'summary': 'Get Message. Pulls a message from the receive queue.', 'source': 'Dell RE doc + binary', 'name': 'GetMessage'},
    (6, 53): {'summary': 'Read Event Message Buffer. Pulls a SEL event the BMC saw.', 'source': 'Dell RE doc + binary', 'name': 'ReadEventMessageBuffer'},
    (6, 55): {'summary': 'Get System GUID. 16 bytes. Dell uses first 6 to identify BMC vendor (KIRA-BMC, Hermon-AMI, Hermon-ATEN).', 'source': 'Dell RE doc + binary', 'name': 'GetSystemGUID'},
    (6, 60): {'summary': 'Close Session. Ends the IPMI 1.5/2.0 session.', 'source': 'Dell RE doc + binary', 'name': 'CloseSession'},
    (6, 61): {'summary': "Get Session Info. Returns who's connected: src IP, MAC, user, channel, priv level.", 'source': 'Dell RE doc + binary', 'name': 'GetSessionInfo'},
    (6, 63): {'summary': 'Get AuthCode. Generates an MD5/MD2 auth code for a payload — debug primitive.', 'source': 'Dell RE doc + binary', 'name': 'GetAuthCode'},
    (6, 64): {'summary': '★★ Set Channel Access. Writes per-channel access mode (always-avail / shared / disabled) + privilege level.', 'source': 'Dell RE doc + binary', 'name': 'SetChannelAccess'},
    (6, 65): {'summary': 'Get Channel Access.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelAccess'},
    (6, 66): {'summary': 'Get Channel Info. Returns medium type (LAN/serial/SOL), session support, IPMI revision per-channel.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelInfo'},
    (6, 67): {'summary': '★★ Set User Access. Writes per-user-per-channel privilege + enable bits.', 'source': 'Dell RE doc + binary', 'name': 'SetUserAccess'},
    (6, 68): {'summary': 'Get User Access. Returns max-user-IDs + per-user enable/priv.', 'source': 'Dell RE doc + binary', 'name': 'GetUserAccess'},
    (6, 69): {'summary': '★★ Set User Name. Writes the username string for a given user ID.', 'source': 'Dell RE doc + binary', 'name': 'SetUserName'},
    (6, 70): {'summary': 'Get User Name.', 'source': 'Dell RE doc + binary', 'name': 'GetUserName'},
    (6, 71): {'summary': "★★★ Set User Password. Writes a user's password (cleartext on the wire if not lanplus-encrypted, or via Dell's special handler that stages it in DRAM). **Sub-byte 0x02 = set password.**", 'source': 'Dell RE doc + binary', 'name': 'SetUserPassword'},
    (6, 72): {'summary': 'Activate Payload. Starts an SOL or other payload session.', 'source': 'Dell RE doc + binary', 'name': 'ActivatePayload'},
    (6, 73): {'summary': 'Deactivate Payload. Stops it.', 'source': 'Dell RE doc + binary', 'name': 'DeactivatePayload'},
    (6, 74): {'summary': 'Get Payload Activation Status.', 'source': 'Dell RE doc + binary', 'name': 'GetPayloadActivationStatus'},
    (6, 75): {'summary': 'Get Payload Instance Info.', 'source': 'Dell RE doc + binary', 'name': 'GetPayloadInstanceInfo'},
    (6, 76): {'summary': 'Set User Payload Access. ★ which payload types each user can use (SOL, OEM).', 'source': 'Dell RE doc + binary', 'name': 'SetUserPayloadAccess'},
    (6, 77): {'summary': 'Get User Payload Access. Live: 0xC7 (needs channel + UID).', 'source': 'Dell RE doc + binary', 'name': 'GetUserPayloadAccess'},
    (6, 78): {'summary': 'Get Channel Payload Support.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelPayloadSupport'},
    (6, 79): {'summary': 'Get Channel Payload Version.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelPayloadVersion'},
    (6, 80): {'summary': 'Get Channel OEM Payload Info.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelOEMPayloadInfo'},
    (6, 82): {'summary': '★★★ Master Write-Read (I2C). **Direct I2C bus access from BMC.** Reach VRMs, SPD ROMs, CPLD, PMBus PSUs, sensor chips. data[0]=bus#, data[1]=slave addr, data[2]=read count, data[3+]=write bytes.', 'source': 'Dell RE doc + binary', 'name': 'MasterWriteRead'},
    (6, 82, 4, 144, 0): {'summary': 'Master Write-Read I2C: read LM75 temp sensor (channel 4, addr 0x90, register 0x00 - temp). T710-confirmed.', 'source': 'Dell RE doc + binary', 'name': 'MasterWRLM75Temp'},
    (6, 82, 4, 144, 2): {'summary': 'Master Write-Read I2C: read LM75 Tos register (channel 4, addr 0x90, reg 0x02). T710-confirmed.', 'source': 'Dell RE doc + binary', 'name': 'MasterWRLM75Tos'},
    (6, 82, 8, 176, 0): {'summary': 'Master Write-Read I2C: PMBus PSU READ_VIN/VOUT/IIN/IOUT etc (channel 8, addr 0xB0). T710-confirmed.', 'source': 'Dell RE doc + binary', 'name': 'MasterWRPMBusBus08'},
    (6, 82, 8, 176, 2): {'summary': 'Master Write-Read I2C: PMBus PSU READ_VOUT (channel 8, addr 0xB0, cmd 0x8B).', 'source': 'Dell RE doc + binary', 'name': 'MasterWRPMBusVoutMode'},
    (6, 82, 8, 176, 16): {'summary': 'Master Write-Read I2C: PMBus PSU MFR_MODEL (channel 8, addr 0xB0, cmd 0x9A).', 'source': 'Dell RE doc + binary', 'name': 'MasterWRPMBusFanCmd'},
    (6, 82, 255, 194, 1): {'summary': '★ Master Write-Read I2C: bus 0xff (out of range) — sets G_u8boot_block_accss_in_prog=1 in fw, returns 0x82. Internal-flag-poke side effect.', 'source': 'Dell RE doc + binary', 'name': 'MasterWRBusFFTrigger'},
    (6, 84): {'summary': 'Get Channel Cipher Suites. Lists supported RMCP+ cipher suites — cipher 0 advertised here = vulnerable.', 'source': 'Dell RE doc + binary', 'name': 'GetChannelCipherSuites'},
    (6, 85): {'summary': '★ Suspend/Resume Payload Encryption.', 'source': 'Dell RE doc + binary', 'name': 'SuspendResumePayloadEncryption'},
    (6, 86): {'summary': '★★ Set Channel Security Keys. Sets the K_R / K_G keys used for IPMI 2.0 RMCP+ session establishment.', 'source': 'Dell RE doc + binary', 'name': 'SetChannelSecurityKeys'},
    (6, 96): {'summary': 'Set Command Enables.', 'source': 'Dell RE doc + binary', 'name': 'SetCommandEnables'},
    (6, 97): {'summary': 'Get Command Enables.', 'source': 'Dell RE doc + binary', 'name': 'GetCommandEnables'},
    (6, 98): {'summary': 'Set Command Sub-function Enables.', 'source': 'Dell RE doc + binary', 'name': 'SetCommandSubFunctionEnables'},
    (6, 99): {'summary': 'Get Command Sub-function Enables.', 'source': 'Dell RE doc + binary', 'name': 'GetCommandSubFunctionEnables'},
    (6, 100): {'summary': 'Get OEM NetFn IANA Support.', 'source': 'Dell RE doc + binary', 'name': 'GetOEMNetFnIANASupport'},
    (8, 2): {'summary': '★★★ CmdFirmwareUpdate. Initiate the BMC firmware-update process. Followed by Phase1/Phase2 chunked write. **Wrong image → BMC brick.**', 'source': 'Dell RE doc + binary'},
    (8, 16): {'summary': '★★★ CmdFirmwareUpdatePhase1. Chunked firmware-image upload (early phase). Session-less per Dell impl.', 'source': 'Dell RE doc + binary'},
    (8, 17): {'summary': '★★★ CmdFirmwareUpdatePhase2. Continued chunked upload.', 'source': 'Dell RE doc + binary'},
    (8, 18): {'summary': 'CmdGetFirmwareUpdateStatus. Poll while update in flight.', 'source': 'Dell RE doc + binary'},
    (8, 19): {'summary': 'CmdGetFirmwareVersion. Read currently-running BMC fw version.', 'source': 'Dell RE doc + binary'},
    (8, 20): {'summary': '★★ CmdRollbackFirmwareVersion. Roll back to previous BMC fw image (kept in spare flash bank). **Forensic-evasion primitive.**', 'source': 'Dell RE doc + binary'},
    (8, 21): {'summary': '★ CmdCancelFirmwareUpdate. Aborts an in-flight update. Useful if Phase1/Phase2 wedged.', 'source': 'Dell RE doc + binary'},
    (8, 22): {'summary': "★★ CmdSetFWImageStatus. Marks one fw bank as 'good' or 'bad' — affects boot bank selection.", 'source': 'Dell RE doc + binary'},
    (10, 16): {'summary': 'Get FRU Inventory Info. T710: 4096 bytes, byte-access.', 'source': 'Dell RE doc + binary', 'name': 'GetFRUInventoryAreaInfo'},
    (10, 17): {'summary': 'Read FRU Data. Pulls bytes from FRU inventory area.', 'source': 'Dell RE doc + binary', 'name': 'ReadFRUData'},
    (10, 18): {'summary': '★★ Write FRU Data. **Can rewrite serial numbers, asset tags, MAC bindings stored in FRU.**', 'source': 'Dell RE doc + binary', 'name': 'WriteFRUData'},
    (10, 32): {'summary': 'Get SDR Repository Info. T710: 126 SDRs, 1505 bytes free, v1.5.', 'source': 'Dell RE doc + binary', 'name': 'GetSDRRepositoryInfo'},
    (10, 34): {'summary': 'Reserve SDR Repository. Returns 2-byte reservation ID required for cmds 0x23/0x26.', 'source': 'Dell RE doc + binary', 'name': 'ReserveSDRRepository'},
    (10, 35): {'summary': 'Get SDR. Read SDR by ID. Reservation-protected.', 'source': 'Dell RE doc + binary', 'name': 'GetSDR', 'reservation_from': 'Reserve SDR Repository (0x0A 0x22) returns the reservation ID (echoed in resp bytes 1-2)'},
    (10, 37): {'summary': 'Partial Add SDR. T710: DISABLED (Dell stub returns 0xC1).', 'source': 'Dell RE doc + binary', 'name': 'PartialAddSDR'},
    (10, 38): {'summary': '★ Delete SDR Entry. Reservation-protected (Reserve SDR Repository = 0x0A 0x22). **Tamper with SDR repo entries — alters the sensor list visible to monitoring.**', 'source': 'Dell RE doc + binary', 'name': 'DeleteSDR', 'reservation_from': 'Reserve SDR Repository (0x0A 0x22) returns the reservation ID'},
    (10, 39): {'summary': 'Clear SDR Repository. T710: DISABLED (Dell stub returns 0xC1).', 'source': 'Dell RE doc + binary', 'name': 'ClearSDRRepository'},
    (10, 40): {'summary': 'Get SDR Repository Time.', 'source': 'Dell RE doc + binary', 'name': 'GetSDRRepositoryTime'},
    (10, 41): {'summary': 'Set SDR Repository Time.', 'source': 'Dell RE doc + binary', 'name': 'SetSDRRepositoryTime'},
    (10, 44): {'summary': 'Run Initialization Agent. Re-runs sensor init.', 'source': 'Dell RE doc + binary', 'name': 'RunInitializationAgent'},
    (10, 64): {'summary': 'Get SEL Info. Repo size, free space, oldest/newest record IDs.', 'source': 'Dell RE doc + binary', 'name': 'GetSELInfo'},
    (10, 66): {'summary': 'Reserve SEL. Returns 2-byte reservation ID for 0x46.', 'source': 'Dell RE doc + binary', 'name': 'ReserveSEL'},
    (10, 67): {'summary': 'Get SEL Entry. Reservation-protected (gates concurrent walks).', 'source': 'Dell RE doc + binary', 'name': 'GetSELEntry'},
    (10, 68): {'summary': '★ Add SEL Entry. **Useful for SEL log spoofing.**', 'source': 'Dell RE doc + binary', 'name': 'AddSELEntry'},
    (10, 70): {'summary': '★★ Delete SEL Entry. Reservation-protected (Reserve SEL = 0x0A 0x42). **Selective log-tamper — target specific events without wiping the whole SEL (which Clear SEL 0x0A 0x47 would).**', 'source': 'Dell RE doc + binary', 'name': 'DeleteSELEntry', 'reservation_from': 'Reserve SEL (0x0A 0x42) returns the reservation ID'},
    (10, 71): {'summary': '★★ Clear SEL. Wipes the BMC event log. **Post-compromise log-cleanup primitive.**', 'source': 'Dell RE doc + binary', 'name': 'ClearSEL'},
    (10, 72): {'summary': 'Get SEL Time. Live: returns Unix time.', 'source': 'Dell RE doc + binary', 'name': 'GetSELTime'},
    (10, 73): {'summary': 'Set SEL Time. ★ Time-skewing changes SEL timestamps.', 'source': 'Dell RE doc + binary', 'name': 'SetSELTime'},
    (12, 1): {'summary': '★★ Set LAN Configuration Parameters. Writes IP, mask, gateway, MAC, VLAN, DHCP, RMCP+ keys, etc.', 'source': 'Dell RE doc + binary', 'name': 'SetLANConfigurationParameters'},
    (12, 2): {'summary': 'Get LAN Configuration Parameters. Read-side of the same parameter table.', 'source': 'Dell RE doc + binary', 'name': 'GetLANConfigurationParameters'},
    (12, 16): {'summary': '★★ Set Serial/Modem Configuration.', 'source': 'Dell RE doc + binary', 'name': 'SetSerialModemConfiguration'},
    (12, 17): {'summary': 'Get Serial/Modem Configuration.', 'source': 'Dell RE doc + binary', 'name': 'GetSerialModemConfiguration'},
    (12, 18): {'summary': 'Set Serial/Modem Mux. Switches the serial port between BMC and host.', 'source': 'Dell RE doc + binary', 'name': 'SetSerialModemMux'},
    (12, 28): {'summary': 'Set Serial Routing Mux. Per-channel BMC/host serial routing.', 'source': 'Dell RE doc + binary', 'name': 'SetSerialRoutingMux'},
    (12, 33): {'summary': '★★ Set SOL Configuration. Auth, encryption, retry, character intervals.', 'source': 'Dell RE doc + binary', 'name': 'SetSOLConfigurationParameters'},
    (12, 34): {'summary': 'Get SOL Configuration.', 'source': 'Dell RE doc + binary', 'name': 'GetSOLConfigurationParameters'},
    (46, 1, 162, 2, 0): {'summary': 'ResvExtendedConfigure: returns reservation ID for the GetExtendedConfigure / SetExtendedConfigure flow. IANA-prefix mandatory.', 'source': 'Dell RE doc + binary', 'name': 'ResvExtendedConfigure'},
    (46, 2): {'reservation_from': 'ResvExtendedConfigure (0x2E 0x01) returns the reservation ID. Without it: CC=0xC5.'},
    (46, 2, 162, 2, 0): {'summary': 'GetExtendedConfigure: read Dell internal config var. Needs reservationID from 0x2E 0x01.', 'source': 'Dell RE doc + binary', 'name': 'GetExtendedConfigure'},
    (46, 3): {'reservation_from': 'ResvExtendedConfigure (0x2E 0x01) returns the reservation ID. Without it: CC=0xC5.'},
    (46, 3, 162, 2, 0): {'summary': '★★ SetExtendedConfigure: write Dell internal config var. Needs reservationID from 0x2E 0x01. **Modifies BMC settings outside the std spec — racadm uses this.**', 'source': 'Dell RE doc + binary', 'name': 'SetExtendedConfigure'},
    (46, 4, 162, 2, 0): {'summary': 'POSTEvent: notify BMC of host-side BIOS POST event. IANA-prefix mandatory.', 'source': 'Dell RE doc + binary', 'name': 'POSTEvent'},
    (46, 7): {'summary': 'CmdTerminalSYS: Dell terminal-mode access entry. Used for serial-redirect / OOB shell sessions. **Not all builds wire this — T710 returns 0xC1.**', 'source': 'Dell RE doc + binary', 'name': 'CmdTerminalSYS'},
    (46, 8): {'summary': '★★ CmdTerminalSYSDRAC: Dell terminal-mode access for DRAC-side shell. Like 0x2E 0x07 but DRAC-targeted. **If active, gives serial-redirected shell access — admin-priv only.**', 'source': 'Dell RE doc + binary', 'name': 'CmdTerminalSYSDRAC'},
    (46, 33): {'summary': 'CmdResetToDefault: stub handler in fullfw (handler addr 0x00188484 = NotSupportRequestHandle on T710 Dell).', 'source': 'Dell RE doc + binary', 'name': 'CmdResetToDefaultStub'},
    (46, 204): {'summary': '★★★ CmdOSAOEMCmdHandler: Avocent OSA dispatcher (IANA 11102 prefix 0x5E 0x2B 0x00 — NOT Dell IANA). 9 sub-cmds: GetFWVersion/ID, SensorTest, **SetSysGUID** (silent rebrand), **SetBMCSA** (change IPMB slave addr), **CmdResetToDefaultOSA** (alt factory-reset DESTRUCTIVE), MemoryChk. Full writeup: Dell iDRAC OEM command deep-dives (internal RE).', 'source': 'Dell RE doc + binary', 'name': 'CmdOSAOEMCmdHandler'},
    (48, 0): {'summary': 'CmdOEMGetChassisCapabilities: Dell-extended GetChassisCaps (extra bytes vs std 0x00 0x00). T710: 0xC1 on LAN — kcs/host-side only.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetChassisCapabilities'},
    (48, 1): {'summary': '★ DellCmdGetChassisStatus: Dell-extended GetChassisStatus. Returns extended status fields beyond std (LCD state, identify state, idrac present flags, etc.).', 'source': 'Dell RE doc + binary', 'name': 'DellCmdGetChassisStatus'},
    (48, 2): {'summary': '★ DellCmdChassisControl: Dell-extended chassis control. Adds Dell-specific actions (graceful shutdown w/ OS coordination via OMSA, etc.).', 'source': 'Dell RE doc + binary', 'name': 'DellCmdChassisControl'},
    (48, 4): {'summary': 'CmdOEMChassisIdentify: Dell-extended identify with extra params (intensity, blink-pattern). T710: KCS-only.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMChassisIdentify'},
    (48, 5): {'summary': '★★ CmdOEMSetChassisCapabilities: write Dell chassis cap flags. T710: not on LAN.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMSetChassisCapabilities'},
    (48, 6): {'summary': 'CmdSetPowerRestorePolicy: configure auto-power-on after AC restore. data[0]: 0x00=stay-off / 0x01=last-state / 0x02=on.', 'source': 'Dell RE doc + binary', 'name': 'CmdSetPowerRestorePolicy'},
    (48, 10): {'summary': 'DellCmdSetFrntPanelState: enable/disable front-panel buttons (power, reset, identify) + LCD lock.', 'source': 'Dell RE doc + binary', 'name': 'DellCmdSetFrntPanelState'},
    (48, 24): {'summary': 'CmdGetBladeID: returns blade slot ID. **Modular chassis only** — fails 0xC1 on rack/tower.', 'source': 'Dell RE doc + binary', 'name': 'CmdGetBladeID'},
    (48, 28): {'summary': "★★★ DellCmdReadWriteLCD: read/write text on the front-panel LCD. **Social-engineering primitive (write 'HARDWARE FAILURE — CALL SUPPORT' to deceive operators).** sub 0x00=read; sub 0x01 0x00 0x00=write.", 'source': 'Dell RE doc + binary', 'name': 'DellCmdReadWriteLCD'},
    (48, 32): {'summary': 'CmdOEMGetSDRRepoInfo: Dell-extended SDR repo info (alt path; live on T710 returns same as 0x0A 0x20).', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetSDRRepoInfo'},
    (48, 33): {'summary': '★★★ CmdResetToDefault: factory-default the BMC. **DESTRUCTIVE — wipes user creds, network config, SSL certs, OEM config.** Companion path: 0x2E 0xCC sub 0x0A01 (CmdResetToDefaultOSA).', 'source': 'Dell RE doc + binary', 'name': 'CmdResetToDefault'},
    (48, 34): {'summary': 'DellCmdGetSOLConfiguration: Dell-extended SOL config get. Live: returns empty (success).', 'source': 'Dell RE doc + binary', 'name': 'DellCmdGetSOLConfiguration'},
    (48, 36): {'summary': '★ DellSetTeamingMode: NIC teaming (LOM1/LOM2/shared/failover/dedicated). Affects the LOM the iDRAC uses for management.', 'source': 'Dell RE doc + binary', 'name': 'DellSetTeamingMode'},
    (48, 37): {'summary': 'DellGetTeamingMode: read current LOM mode.', 'source': 'Dell RE doc + binary', 'name': 'DellGetTeamingMode'},
    (48, 38): {'summary': 'DellCmdMTFL: Multi-Tenant FL? Modular Test Function Level? Live: 0xC7.', 'source': 'Dell RE doc + binary', 'name': 'DellCmdMTFL'},
    (48, 39): {'summary': '★★ DellGetInternalVariable: backend racadm config-var read. Sub-bytes select var index. **Reads Dell internal config (boot mode, BIOS settings, lifecycle state). T710-confirmed via sub 0x01-0x04.**', 'source': 'Dell RE doc + binary', 'name': 'DellGetInternalVariable'},
    (48, 48): {'summary': '★ DellSetFanControlParameters: adjust fan-control PID/curve constants.', 'source': 'Dell RE doc + binary', 'name': 'DellSetFanControlParameters'},
    (48, 49): {'summary': 'DellGetFanControlParameters: read fan-control config.', 'source': 'Dell RE doc + binary', 'name': 'DellGetFanControlParameters'},
    (48, 50): {'summary': 'DellQueryChassisIdentifyStatus: read identify-LED state.', 'source': 'Dell RE doc + binary', 'name': 'DellQueryChassisIdentifyStatus'},
    (48, 51): {'summary': 'DellQueryGetCPLDRevision: read CPLD firmware revision.', 'source': 'Dell RE doc + binary', 'name': 'DellQueryGetCPLDRevision'},
    (48, 55): {'summary': 'CmdReleaseKVM: release Virtual KVM session ownership. Modular-only.', 'source': 'Dell RE doc + binary', 'name': 'CmdReleaseKVM'},
    (48, 56): {'summary': 'CmdSetKVMOwner: assign Virtual KVM ownership. Modular-only.', 'source': 'Dell RE doc + binary', 'name': 'CmdSetKVMOwner'},
    (48, 57): {'summary': 'CmdGetKVMRevision: read iKVM firmware version. Modular-only.', 'source': 'Dell RE doc + binary', 'name': 'CmdGetKVMRevision'},
    (48, 81): {'summary': "★ CmdGetHostEventStatus: live host-side event status (BIOS, POST). Live T710: '03 00 00 00 00'.", 'source': 'Dell RE doc + binary', 'name': 'CmdGetHostEventStatus'},
    (48, 135): {'summary': 'CmdGetServerBladePowerWatt: per-blade power draw. **Modular only**.', 'source': 'Dell RE doc + binary', 'name': 'CmdGetServerBladePowerWatt'},
    (48, 139): {'summary': 'CmdSendBladeCPUThrottle: blade-side CPU throttle command. **Modular only — fails 0xC1 on rack/tower.**', 'source': 'Dell RE doc + binary', 'name': 'CmdSendBladeCPUThrottle'},
    (48, 140): {'summary': 'DellGetFanSpeedCtrLevel: read current fan-speed control level setting.', 'source': 'Dell RE doc + binary', 'name': 'DellGetFanSpeedCtrLevel'},
    (48, 141): {'summary': '★ DellSetChassisFanStatus: write chassis fan status register. **Spoofing/altering this affects automatic thermal-protection logic.**', 'source': 'Dell RE doc + binary', 'name': 'DellSetChassisFanStatus'},
    (48, 156): {'summary': 'CmdOEMGetPWRConsumptionData: power-consumption telemetry dispatcher. Sub-bytes select feature (0x07 0x01 = live sample). See sub-byte variant for live data.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetPWRConsumptionData'},
    (48, 156, 7, 1): {'summary': 'CmdOEMGetPWRConsumptionData (sub 0x07 0x01): live power-consumption sample. T710-confirmed.', 'source': 'Dell RE doc + binary', 'name': 'DellOEMGetPWRConsumptionPSU'},
    (48, 157): {'summary': "★ CmdOEMResetPwrConsumptionDataCounters: zero the cumulative power-counters. Forensic-evasion if you've been running a power-side-channel attack.", 'source': 'Dell RE doc + binary', 'name': 'CmdOEMResetPwrConsumptionDataCounters'},
    (48, 160): {'summary': 'CmdGetSoftLockStatus: read BMC soft-lock state (Dell config-write-protect mode).', 'source': 'Dell RE doc + binary', 'name': 'CmdGetSoftLockStatus'},
    (48, 161): {'summary': '★ CmdOEMPOSTMASERAccess: MASER access during host-POST. BIOS uses this to read/stage inventory the BMC provides.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMPOSTMASERAccess'},
    (48, 162): {'summary': '★★★ CmdOEMMASERPartitionAccess: read/write the MASER eMMC partition. **NV-storage primitive — corrupt iDRAC config / Lifecycle Controller logs / hardware inventory.**', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMMASERPartitionAccess'},
    (48, 163): {'summary': '★ CmdOEMRemoteEnablement: zero-touch / auto-discovery provisioning helper. Reachable on LAN.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMRemoteEnablement'},
    (48, 164): {'summary': '★ CmdOEMvFlash: virtual-flash (vFlash SD card) management. SD-card image partition control.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMvFlash'},
    (48, 165): {'summary': '★★★ CmdOEMDellFactory: factory provisioning — recreates hw inventory + may reset settings. **DESTRUCTIVE.**', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMDellFactory'},
    (48, 166): {'summary': '★★★ CmdOEMBackupRestore: backup/restore BMC NVRAM. **Roll back configuration changes OR stage a backdoor that survives reset.**', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMBackupRestore'},
    (48, 169): {'summary': 'CmdOEMMASERBonding: MASER-side bonding state.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMMASERBonding'},
    (48, 170): {'summary': '★★ CmdOEMMASERLCLAccess: Lifecycle Controller log access via MASER. **Read AND write LCL — log-tamper primitive.**', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMMASERLCLAccess'},
    (48, 171): {'summary': 'CmdOEMGetMASERInfo: read MASER (eMMC) layout / partition info.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetMASERInfo'},
    (48, 172): {'summary': '★★★ CmdOEMRecreateMASER: WIPE + recreate MASER (eMMC) partition table. **DESTRUCTIVE — loses LCL, hw inventory, factory data.**', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMRecreateMASER'},
    (48, 173): {'summary': 'CmdOEMGetMASERType: enumerate MASER device type/variant.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetMASERType'},
    (48, 174): {'summary': 'CmdOEMGetMASERAccessState: query MASER access state.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMGetMASERAccessState'},
    (48, 175): {'summary': '★★ CmdOEMSetMASERAccessState: enable/disable MASER access. Disabling kills LCL writes — silent forensic disable.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMSetMASERAccessState'},
    (48, 176): {'summary': 'DellCmdPowerSupplyInfo: per-PSU info dump.', 'source': 'Dell RE doc + binary', 'name': 'DellCmdPowerSupplyInfo'},
    (48, 179): {'summary': 'DellCmdPowerConsumption: live power consumption.', 'source': 'Dell RE doc + binary', 'name': 'DellCmdPowerConsumption'},
    (48, 181): {'summary': 'DellCmdGetLCDInfo: read front-panel LCD config + state. Companion of 0x30 0x1C (read/write).', 'source': 'Dell RE doc + binary', 'name': 'DellCmdGetLCDInfo'},
    (48, 182): {'summary': 'CmdOEMPSUFwUpd: PSU firmware-update dispatcher. Real wire: 0x30 0xB6 0x0A 0x01 0x00 + image bytes. See sub-byte variant for full risk note.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMPSUFwUpd'},
    (48, 182, 10, 1, 0): {'summary': '★★ CmdOEMPSUFwUpd: kick off PSU firmware update. PSU index in arg byte 1. **Wrong image → PSU brick.**', 'source': 'Dell RE doc + binary', 'name': 'DellOEMPSUFwUpdInit'},
    (48, 183): {'summary': 'CmdOEMPSUFwUpdStatus: PSU fw-update progress dispatcher. Real wire: 0x30 0xB7 0x0A 0x01.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMPSUFwUpdStatus'},
    (48, 183, 10, 1): {'summary': 'CmdOEMPSUFwUpdStatus: poll PSU firmware-update status.', 'source': 'Dell RE doc + binary', 'name': 'DellOEMPSUFwUpdProgress'},
    (48, 184): {'summary': "DellGetSpdDimmInfo: read DIMM SPD info via the BMC's I2C-to-DIMMs path.", 'source': 'Dell RE doc + binary', 'name': 'DellGetSpdDimmInfo'},
    (48, 185): {'summary': '★★ DellSetSpdDimmInfo: **WRITE DIMM SPD bytes**. SPD is supposed to be RO; if writeable here, can corrupt memory training params.', 'source': 'Dell RE doc + binary', 'name': 'DellSetSpdDimmInfo'},
    (48, 186): {'summary': 'Dell GetPowerCapConfig: power-cap config dispatcher. Real wire: 0x30 0xBA 0x01 0x00 (sub 0x01 = read current).', 'source': 'Dell RE doc + binary', 'name': 'GetPowerCapConfig'},
    (48, 186, 1, 0): {'summary': 'Dell GetPowerCapConfig: read power-cap config (sub 0x01).', 'source': 'Dell RE doc + binary', 'name': 'GetPowerCapConfigCurrent'},
    (48, 187): {'summary': 'Dell GetPowerHeadroom: available power-headroom margin.', 'source': 'Dell RE doc + binary', 'name': 'GetPowerHeadroom'},
    (48, 188): {'summary': 'DellCPLDAccessStatus: CPLD access state probe.', 'source': 'Dell RE doc + binary', 'name': 'DellCPLDAccessStatus'},
    (48, 190): {'summary': '★★★ DellRollbackFW: roll back BMC firmware to backup bank. **Forensic-evasion + downgrade-attack primitive.**', 'source': 'Dell RE doc + binary', 'name': 'DellRollbackFW'},
    (48, 191): {'summary': 'DellGetFWVersion: read BMC firmware version.', 'source': 'Dell RE doc + binary', 'name': 'DellGetFWVersion'},
    (48, 192): {'summary': '★★★ Dell PROCHOTThrottle: force PROCHOT# assertion on host CPU. data1: 0x00=read-state (returns 7 bytes), 0x01=set-state. **CRITICAL — instant CPU throttle (silent DoS).**', 'source': 'Dell RE doc + binary', 'name': 'PROCHOTThrottle'},
    (48, 192, 0): {'summary': 'Dell PROCHOTThrottle: read state. Returns 7 bytes; byte[0]=active flag, byte[1]=throttle mode.', 'source': 'Dell RE doc + binary', 'name': 'DellPROCHOTRead'},
    (48, 192, 1, 0): {'summary': 'Dell PROCHOTThrottle: disable.', 'source': 'Dell RE doc + binary', 'name': 'DellPROCHOTDisable'},
    (48, 192, 1, 1): {'summary': '★★★ Dell PROCHOTThrottle: enable mode 1. **Instant CPU throttle.**', 'source': 'Dell RE doc + binary', 'name': 'DellPROCHOTEnable'},
    (48, 193): {'summary': 'DellGetActiveLOM: which LOM is currently bound to BMC mgmt traffic.', 'source': 'Dell RE doc + binary', 'name': 'DellGetActiveLOM'},
    (48, 194): {'summary': '★★ Dell RIPSControl: PSU redundancy / protection control via I2C-to-PSU. Sub-byte selects op (0x00, 0x05, 0x0a observed).', 'source': 'Dell RE doc + binary', 'name': 'RIPSControl'},
    (48, 195): {'summary': 'CmdEchoControl: BMC echo for IPMI-stack testing. Live: 0xCC right length but wrong content.', 'source': 'Dell RE doc + binary', 'name': 'CmdEchoControl'},
    (48, 196): {'summary': '★★ Dell ThrottleMem: memory throttle (platform-gated to specific Nehalem-EP / AMD CPUs; CC=0xC9 elsewhere).', 'source': 'Dell RE doc + binary', 'name': 'ThrottleMem'},
    (48, 196, 32): {'summary': 'Dell ThrottleMem (sub 0x20). Returns 0xC9 on T710 (unsupported platform).', 'source': 'Dell RE doc + binary', 'name': 'ThrottleMemEnable'},
    (48, 202): {'summary': '★★★ DelleKmsCmdHlder: Dell eKMS dispatcher. Routes IPMI to KMIP client (libskmip.so) for SED key mgmt. Sub-cmds: eKmsGet/SetConfig (KMS server IP/port/device-group), eKmsGetCmdStatus, eKmsGetKMSStatus. **HIGH attack value if chassis runs SEDs+eKMS — eKmsSetConfig redirects boot-time SED unlock to a rogue KMS.** Full writeup: Dell iDRAC OEM command deep-dives (internal RE).', 'source': 'Dell RE doc + binary', 'name': 'DelleKmsCmdHlder'},
    (48, 204): {'summary': 'CmdOEMPwrAvgInterval: averaging-interval config for power-consumption stats.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMPwrAvgInterval'},
    (48, 205): {'summary': 'CmdOEMPwrAvgRange: averaging-range bounds for power-consumption stats.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMPwrAvgRange'},
    (48, 208): {'summary': '★ CmdOEMMiscCmd: Dell misc-OEM dispatcher. Sub-byte selects op (factory/diag mix). Reachable on LAN, payload-gated.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMMiscCmd'},
    (48, 210): {'summary': '★ RacMw_TransferData: RAC middleware data transfer. ★ Used by Dell-side racadm/OMSA agents to ferry blobs (config, certs) — opaque on the wire.', 'source': 'Dell RE doc + binary', 'name': 'RacMw_TransferData'},
    (48, 212): {'summary': 'CmdOEMSPUSCmd: SPUS = ?. Live 0xC7 — needs payload. Dell-internal subsystem.', 'source': 'Dell RE doc + binary', 'name': 'CmdOEMSPUSCmd'},
}
