"""zipmi.scapy_ipmi.oem.supermicro_known_context — full SM audit overlay.

Hand-curated entries from full audit of every Supermicro OEM cmd
plus the std-IPMI cmds Dell ships handlers for. Sources:
  - ~/phd/bmc/supermicro/smcipmitool-decompile/  (cfr decompile)
  - ~/phd/bmc/supermicro/smcipmi-reversing/  (smcipmi RE notes)
  - ~/phd/bmc/supermicro/sm-faq-cmds/notes.json  (58-FAQ corpus)
  - ~/phd/bmc/supermicro/aten-alupdate-firmware-exfil.md
  - ~/phd/bmc/supermicro/smcipmitool-deep-dive.md
  - ~/phd/bmc/supermicro/smcipmitool-cmd-sequences.md

Risk markers (in summary):
  *      interesting / non-obvious behaviour
  **     sensitive (admin escalation surface)
  ***    destructive / critical (data loss, brick, host attack)

Reservation flows: SDR, SEL, BIOS-OOB upload/download (NetFn 0x30 0xa0),
Raritan KVM fw upgrade (NetFn 0x3c 0x21), Raritan vMedia floppy/SMB,
AMI YAFU activate-flash gate (NetFn 0x32 0x10).
"""

KNOWN_CONTEXT: dict[tuple, dict] = {
    (6, 34): {'summary': 'Reset BMC watchdog timer (must be < timeout to avoid reset).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'ResetBMCWatchdog'},
    (6, 55): {'summary': 'Get System GUID.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetSystemGUID'},
    (6, 82, 5, 112, 1): {'summary': '★ Master Write-Read: PMBus PSU monitoring, X7 motherboard variant.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'MasterWriteReadPMBusX7'},
    (6, 82, 7, 112, 1): {'summary': '★ Master Write-Read: PMBus PSU monitoring (ch=7, addr=0x70). FAQ:15411.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'MasterWriteReadPMBus'},
    (6, 82, 7, 114, 1): {'summary': '★ Master Write-Read: PMBus PSU2.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'MasterWriteReadPMBusPSU2'},
    (6, 82, 7, 176): {'summary': '★ Master Write-Read: PMBus PSU status for SBB. FAQ:20660.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'MasterWriteReadPMBusSBB'},
    (10, 34): {'summary': 'CmdResvSDRRepo: returns 2-byte reservation ID. Required for cmds 0x23/0x26.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'CmdResvSDRRepo'},
    (10, 35): {'reservation_from': 'Reserve SDR Repository (0x0A 0x22) returns the reservation ID'},
    (10, 38): {'summary': '★ Delete SDR Entry. Reservation-protected.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'DeleteSDREntry', 'reservation_from': 'Reserve SDR Repository (0x0A 0x22) returns the reservation ID'},
    (10, 66): {'summary': 'CmdReserveSEL: returns 2-byte reservation ID for 0x46.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'CmdReserveSEL'},
    (10, 70): {'reservation_from': 'Reserve SEL (0x0A 0x42) returns the reservation ID'},
    (12, 2): {'summary': 'Get LAN Configuration Parameters.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetLANConfigParams'},
    (46, 64): {'summary': '★★★ sendRawPECI: direct PECI passthrough to host CPU. **Read MSRs (incl. SGX), CR registers, dump SMRAM control state. Most powerful primitive in Intel Node Manager (NM).**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'sendRawPECI'},
    (46, 75): {'summary': '★ getCPUandMemoryTemperature: live CPU/DIMM junction temps via PECI.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getCPUandMemoryTemperature'},
    (46, 100): {'summary': 'getCUPSCapabilities: what CUPS features supported.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getCUPSCapabilities'},
    (46, 101): {'summary': 'getCUPSData: live core/IO/mem-bandwidth %.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getCUPSData'},
    (46, 102): {'summary': '★ setCUPSConfig: sample period, IIO bandwidth thresholds.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setCUPSConfig'},
    (46, 103): {'summary': 'getCUPSConfig.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 104): {'summary': '★ setCUPSPolicy: per-CPU CUPS thresholds.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setCUPSPolicy'},
    (46, 105): {'summary': 'getCUPSPolicy.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 128): {'summary': 'getBootGuardVersion: BootGuard fw version.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getBootGuardVersion'},
    (46, 129): {'summary': 'getBootGuardCapability: BootGuard mode (Verified / Measured / Both).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getBootGuardCapability'},
    (46, 130): {'summary': '★ getBootGuardHealth: tick count of BootGuard verification failures. Trust-state probe.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getBootGuardHealth'},
    (46, 168): {'summary': 'getImageInventory: loaded ME firmware-image manifest.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getImageInventory'},
    (46, 192): {'summary': '★★ enableDisableNodeManagerPolicyControl: master toggle for Node Manager policies.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'enableDisableNodeManagerPolicyControl'},
    (46, 193): {'summary': '★★★ setNodeManagerPolicy: power-cap config (W, correction time, trigger limit, statistics period). **Silent DoS — drop server into 50W cap; CPU runs but slowly.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setNodeManagerPolicy'},
    (46, 194): {'summary': 'getNodeManagerPolicy.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 195): {'summary': '★ setNodeManagerAlertThresholds.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 196): {'summary': 'getNodeManagerAlertThresholds.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 197): {'summary': '★ setNodeManagerPolicySuspendPeriods: time-of-day suspend windows.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setNodeManagerPolicySuspendPeriods'},
    (46, 198): {'summary': 'getNodeManagerPolicySuspendPeriods.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 199): {'summary': '★ resetNodeManagerStatistics: zero stats per (mode, domain, policy). Forensic-evasion if power side-channel attack used.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'resetNodeManagerStatistics'},
    (46, 200): {'summary': 'getNodeManagerStatistics: avg/min/max/curr power, throttle dwell time.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getNodeManagerStatistics'},
    (46, 201): {'summary': 'getNodeManagerCapabilities.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 202): {'summary': 'getNodeManagerVersion: Node Manager / ME firmware version.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getNodeManagerVersion'},
    (46, 203): {'summary': '★★ setNodeManagerPowerDrawRange: min/max per-domain power-draw (W). Bound the policy authority.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setNodeManagerPowerDrawRange'},
    (46, 204): {'summary': '★★ setTurboSynchronizationRatio: per-socket per-active-cores turbo ratio limit. Cap turbo headroom.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setTurboSynchronizationRatio'},
    (46, 205): {'summary': 'getTurboSynchronizationRatio.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 206): {'summary': '★ setNodeManagerAlertDestination: SNMP/PEF alert dest.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setNodeManagerAlertDestination'},
    (46, 207): {'summary': 'getNodeManagerAlertDestination.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 208): {'summary': '★★ setTotalPowerBudgetRequest: rack/chassis-level total power cap.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setTotalPowerBudgetRequest'},
    (46, 209): {'summary': 'getTotalPowerBudgetRequest.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 210): {'summary': '★★★ setMaxAllowedCPUCoresState / setMaxAllowedCPU_P_T_State: cap online cores OR cap CPU P-state / T-state. **Silent DoS — restrict to 1 P-state.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setMaxAllowedCPUCoresState'},
    (46, 211): {'summary': 'getMaxAllowedCPUCores / getMaxAllowedCPU_P_T_State.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getMaxAllowedCPUCores'},
    (46, 212): {'summary': 'getNumberOf_P_T_StateRequest: pending P/T-state cap requests.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getNumberOf_P_T_StateRequest'},
    (46, 220): {'summary': '★★ setMEPowerState: force ME into specified power state (S0/S1/S5).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setMEPowerState'},
    (46, 222): {'summary': 'getMEFWCapabilities.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (46, 223): {'summary': '★★★ forceMERecovery: flip ME into recovery mode. **Post-exploit reset / unwedge tampered ME.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'forceMERecovery'},
    (46, 234): {'summary': 'getHostCPUData: read CPU vendor/family/stepping/capabilities via ME.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getHostCPUData'},
    (46, 254): {'summary': 'getCurrentNMStatus: live Node Manager op status.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getCurrentNMStatus'},
    (48, 33): {'summary': '★ getProductID: read SM product code.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetProductID'},
    (48, 33, 1): {'summary': '★ Get LAN1 MAC address (or product ID lookup variant).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetLAN1MAC'},
    (48, 33, 2): {'summary': '★ Get LAN2 MAC address.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetLAN2MAC'},
    (48, 55): {'summary': '★ Get IPMI Mgr System GUID (16B). First 6B identify BMC type (KIRA-BMC, Hermon-AMI, Hermon-ATEN). Same FAQ:13155 analysis as Dell.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetIPMIMgrSystemGUID'},
    (48, 64): {'summary': '★★ Reset to factory (alt path, see 0x30 0x99).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'FactoryResetAlt'},
    (48, 65): {'summary': '★★★ Factory-default the BMC. **DESTRUCTIVE — wipes ALL settings + SSL cert + AD/LDAP/users.** FAQ:14553.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'FactoryDefaultBMC'},
    (48, 69): {'summary': '★ Set/Get fan-speed mode. data1=0(Get)/1(Set), data2=0(Std)/1(Full)/2(Optimal).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'FanSpeedMode'},
    (48, 72, 1): {'summary': "★★★ Reset BMC creds → ADMIN/ADMIN. **In-band only (won't run over LAN). On a compromised host: trivial cred reset.** FAQ:30311.", 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'ResetBMCCredsAdmin'},
    (48, 104): {'summary': '★★ Clear cert (cmd alone with sub 0/0).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'ClearCert'},
    (48, 104, 7): {'summary': "★★★ IPv6 config — calls LanConfigApply path which has shell-injection bug per smcipmi RE. **HIGH RISK — vector for cmd injection on the BMC's Linux side.**", 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'IPv6Config'},
    (48, 104, 16): {'summary': '★★★ Network config — LanConfigApply path; same shell-injection vector as 0x07.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'NetworkConfig'},
    (48, 112, 16): {'summary': '★★★ OEMStartFWUpgradeCmd: start SM BMC fw upgrade (X10/X11+ family). data[1]=device_type (0=BMC, 1=BIOS, 2=...). Pair with 0x11/0x12.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'OEMStartFWUpgradeCmd'},
    (48, 112, 17): {'summary': '★★★ OEMUploadFWChunk: chunked write to staged flash.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'OEMUploadFWChunk'},
    (48, 112, 18): {'summary': '★★★ OEMFlashFWCmd: triggers flash. **Calls system() — RCE bug per smcipmi RE if data is attacker-controlled.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'OEMFlashFWCmd'},
    (48, 112, 21): {'summary': '★ CancelFWUpgrade.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ'},
    (48, 112, 22): {'summary': '★★ FinalizeFWUpgrade: apply + BMC reboot.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'FinalizeFWUpgrade'},
    (48, 112, 38): {'summary': '★ OEMHostNameOperation: set/get system hostname (sub 0x01=set, 0x02=get).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'OEMHostNameOp'},
    (48, 112, 48): {'summary': '★★★ StartRestore (UtilRestoreConfig): restore config from staged file. **format-string in path arg — RCE per EXPLOITS.md.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'StartRestore'},
    (48, 112, 119): {'summary': '★★ GPIO Write: physical-pin control. data: bank + value. Drives motherboard GPIO lines — can affect chassis intrusion detect, custom hardware mods.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GPIOWrite'},
    (48, 112, 183): {'summary': '★ Clear lighttpd.conf (SSL cert reset path). FAQ:14553.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'ClearLighttpdConf'},
    (48, 112, 249): {'summary': '★★ OEMSet/GetProductionKey: factory production key (gates the rest of the 0xfX surface).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'OEMProductionKey'},
    (48, 114, 1, 0): {'summary': '★★★ DISABLE RAKP authentication. **WEAKENS SECURITY — strips IPMI 2.0 strong auth.** FAQ:24528.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'DisableRAKPAuth'},
    (48, 153): {'summary': '★★ Erase unrecognized SDR settings. Wire: 0x30 0x99 0 0 0 0 0 0 0 0 0 0. FAQ:14120.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'EraseUnrecognizedSDR'},
    (48, 159): {'summary': '★ Get LAN2+ MAC addrs starting from LAN2.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetLAN2PlusMAC'},
    (48, 160, 2): {'reservation_from': 'getUploadResvID (0x30 0xa0 0x01) returns the reservation ID'},
    (48, 160, 3): {'reservation_from': 'getUploadResvID (0x30 0xa0 0x01) returns the reservation ID'},
    (48, 160, 4): {'reservation_from': 'getUploadResvID (0x30 0xa0 0x01) returns the reservation ID'},
    (48, 160, 6): {'reservation_from': 'prepareFileDownload (0x30 0xa0 0x05) returns the reservation ID'},
    (48, 160, 7): {'reservation_from': 'prepareFileDownload (0x30 0xa0 0x05) returns the reservation ID'},
    (48, 160, 8): {'reservation_from': 'prepareFileDownload (0x30 0xa0 0x05) returns the reservation ID'},
    (48, 226): {'summary': '★ Get IPMI power consumption (Intel ME-reported). Wire: 0x30 0xe2 0 0 0.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'GetIPMIPowerConsumption'},
    (50, 1): {'summary': '★ getFlashInfo: flash chip ID, size, sector layout. AMI YAFU envelope.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getFlashInfo'},
    (50, 2): {'summary': '★ getFirmwareInfo: currently-running BMC fw version + build.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getFirmwareInfo'},
    (50, 3): {'summary': '★ getFMHInfo: Flash Module Header — partition table on chip.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getFMHInfo'},
    (50, 4): {'summary': 'getStatus: AMI YAFU op status.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getStatus'},
    (50, 16): {'summary': '★★★ activateFlashMode: GATE primitive. Once accepted, R/W/E unlocked. Polled with up-to-12 retries × 10s on CC=0x13 (busy). **Without this, all subsequent flash ops fail.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'activateFlashMode'},
    (50, 32): {'summary': '★ allocateMemory: reserve a buffer in BMC RAM; returns address.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'allocateMemory'},
    (50, 33): {'summary': 'freeMemory: free a previously-allocated BMC RAM buffer.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'freeMemory'},
    (50, 34): {'summary': "★★★ readFlash: raw flash read at (offset, width, size). **Bypass for 'firmware encrypted at rest' assumptions — pulls plaintext flash bytes via IPMI.**", 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'readFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first; CC=0x13 (busy) until then'},
    (50, 35): {'summary': '★★★ writeFlash: raw flash write. **Modify BMC firmware byte-by-byte over IPMI. Wrong write → BMC brick.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'writeFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first'},
    (50, 36): {'summary': '★★★ eraseFlash: erase a flash block. Pair with writeFlash to overwrite specific regions.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'eraseFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first'},
    (50, 37): {'summary': '★★ protectFlash: set/clear flash write-protect on a block.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'protectFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first'},
    (50, 38): {'summary': "★★★ eraseCopyFlash: atomic erase+write from BMC RAM into flash. **Most efficient 'patch the firmware' primitive.**", 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'eraseCopyFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first'},
    (50, 39): {'summary': '★★ verifyFlash: compare BMC RAM region vs flash region.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'verifyFlash', 'reservation_from': 'activateFlashMode (0x32 0x10) must succeed first'},
    (50, 40): {'summary': 'getECFStatus: erase/compute/flash op status (long ops poll this).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getECFStatus'},
    (50, 41): {'summary': 'getVerifyStatus: verify-op status.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getVerifyStatus'},
    (50, 48): {'summary': '★★★ readMemory: raw BMC kernel-space RAM read. **Live secrets / live keys / kernel data.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'readMemory'},
    (50, 49): {'summary': '★★★ writeMemory: raw BMC kernel-space RAM write. **Privilege escalation primitive — patch kernel data, hook interrupts.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'writeMemory'},
    (50, 50): {'summary': '★★ copyMemory: RAM → RAM copy.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'copyMemory'},
    (50, 51): {'summary': 'compareMemory: RAM region equality test.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'compareMemory'},
    (50, 52): {'summary': '★ clearMemory: zero a RAM region.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'clearMemory'},
    (50, 64): {'summary': '★ getBootConfig: read U-Boot env var.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getBootConfig'},
    (50, 65): {'summary': '★★ setBootConfig: write U-Boot env var. Persist boot-time config changes.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setBootConfig'},
    (50, 66): {'summary': '★ getBootVars: read U-Boot env (often factory keys, recovery passwords).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getBootVars'},
    (50, 67): {'summary': 'getDNSServer: read configured DNS servers.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getDNSServer'},
    (50, 68): {'summary': '★★ setDNSServer: write DNS servers. **Redirect BMC DNS for service downloads / log destinations.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setDNSServer'},
    (50, 80): {'summary': 'deactivateFlash: exit flash mode (variant 1).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'deactivateFlash'},
    (50, 81): {'summary': 'deactivateFlash: exit flash mode (variant 2).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'deactivateFlash'},
    (60, 32): {'summary': 'getFirmwareVersion: Raritan KVM fw version (NOT BMC).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getFirmwareVersion'},
    (60, 33): {'summary': '★★ startFirmwareUpgrade: kick off Raritan KVM fw upgrade. Returns reservation ID.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'startFirmwareUpgrade'},
    (60, 34): {'summary': '★★ uploadFirmware: chunked KVM fw upload. Reservation-protected.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'uploadFirmware', 'reservation_from': 'startFirmwareUpgrade (0x3c 0x21) returns the reservation ID'},
    (60, 35): {'summary': '★★★ flashFirmware: commit uploaded fw to KVM flash. **Wrong image → KVM subsystem brick.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'flashFirmware', 'reservation_from': 'startFirmwareUpgrade (0x3c 0x21) returns the reservation ID'},
    (60, 36): {'summary': 'cancelFirmwareUpgrade: abort in-flight upload.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'cancelFirmwareUpgrade', 'reservation_from': 'startFirmwareUpgrade (0x3c 0x21) returns the reservation ID'},
    (60, 37): {'summary': '★★ finalizeFirmwareUpgrade: apply + KVM-side reboot.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'finalizeFirmwareUpgrade', 'reservation_from': 'startFirmwareUpgrade (0x3c 0x21) returns the reservation ID'},
    (60, 64): {'summary': '★★ resetToFactoryDefaults: KVM-side factory reset (NOT BMC reset).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'resetToFactoryDefaults'},
    (60, 65): {'summary': 'getSerialNumber: Raritan-side serial.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getSerialNumber'},
    (60, 66): {'summary': '★ setSerialNumber: write Raritan-side serial.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setSerialNumber'},
    (60, 80): {'summary': 'getVirtualMediaStatus: per-device state.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getVirtualMediaStatus'},
    (60, 81): {'summary': 'closeVirtualMediaSession: tear down vMedia.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'closeVirtualMediaSession'},
    (60, 82): {'summary': '★ startFloppyImageUpload: begin floppy-image upload to BMC. Returns reservation ID.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'startFloppyImageUpload'},
    (60, 83): {'summary': '★ uploadFloppyImage: chunked floppy bytes.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'uploadFloppyImage', 'reservation_from': 'startFloppyImageUpload (0x3c 0x52) returns the reservation ID'},
    (60, 84): {'summary': '★ finalizeFloppyImageUpload: mount/unmount uploaded floppy.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'finalizeFloppyImageUpload', 'reservation_from': 'startFloppyImageUpload (0x3c 0x52) returns the reservation ID'},
    (60, 85): {'summary': '★ startSMBImageMount: begin SMB-mounted ISO setup. Returns reservation ID.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'startSMBImageMount'},
    (60, 86): {'summary': '★★ setSMBImageParameter: SMB cred / path setup. **Stages remote ISO — could mount attacker-controlled SMB share for boot.**', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'setSMBImageParameter', 'reservation_from': 'startSMBImageMount (0x3c 0x55) returns the reservation ID'},
    (60, 87): {'summary': '★★ finalizeSMBImageMount: mount the SMB image.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'finalizeSMBImageMount', 'reservation_from': 'startSMBImageMount (0x3c 0x55) returns the reservation ID'},
    (62, 9): {'summary': 'getFirmwareBuild: Supermicro fw build number (ASCII).', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'getFirmwareBuild'},
    (62, 29): {'summary': '★★★ AlUpdate FwDumpStart: kick off `/bin/restore_file.sh 0` → `dd if=/dev/mtdblock5` (entire 32MB flash) → /tmp/dump_flash. **CRITICAL — live fw exfil over IPMI. Vendor-supported (no CVE), pre-auth via cipher-0 RMCP+.** Full writeup: ~/phd/bmc/supermicro/aten-alupdate-firmware-exfil.md.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'AlUpdate'},
    (62, 30): {'summary': '★★ AlUpdate FwDumpStatus: poll size; returns 0x01 + 24-bit BE size when ready.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'AlUpdate'},
    (62, 31): {'summary': '★★★ AlUpdate FwDumpRead: stream 55-byte chunks. ~600k iterations to drain whole flash.', 'source': 'smcipmi RE + SMCIPMITool decompile + FAQ', 'name': 'AlUpdate'},
}
